-- A350_Admin_data Clean up

DECLARE @CONTEXT_id_old INT

SELECT @CONTEXT_id_old = CONTEXT_id FROM T_EDIP_CONTEXT WHERE ContextName='A350_Admin_data'

IF EXISTS(SELECT * FROM T_EDIP_LINK_CONTEXT__FEATURE WHERE CONTEXT__FEATURE_CONTEXT_idr=@CONTEXT_id_old)
BEGIN
DELETE FROM T_EDIP_LINK_CONTEXT__FEATURE WHERE CONTEXT__FEATURE_CONTEXT_idr=@CONTEXT_id_old
END
IF EXISTS(SELECT * FROM T_EDIP_LINK_ATTRIBUTE__CONTEXT WHERE ATTRIBUTE__CONTEXT_CONTEXT_idr=@CONTEXT_id_old)
BEGIN
DELETE FROM T_EDIP_LINK_ATTRIBUTE__CONTEXT WHERE ATTRIBUTE__CONTEXT_CONTEXT_idr=@CONTEXT_id_old
END
IF EXISTS(SELECT * FROM T_LINK_CONTEXT__USER WHERE CONTEXT__USER_CONTEXT_idr=@CONTEXT_id_old)
BEGIN
DELETE FROM T_LINK_CONTEXT__USER WHERE CONTEXT__USER_CONTEXT_idr=@CONTEXT_id_old
END
IF EXISTS(SELECT * FROM T_LINK_CONTEXT__DOMAIN WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id_old)
BEGIN
DELETE FROM T_LINK_CONTEXT__DOMAIN WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id_old
END
