DELETE FROM t_choicelist WHERE choicelist = 'FINCategory'
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','AIRLINES SPARE ASSEMBLY',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','DATA TABLE',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','EQUIPMENT MOUNTED IN A DASSY',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','FIN SW SPP',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','FIN LRM TYPE',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','FIN POSITION',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LIGHTED PLATE XXXX VU',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LOAD GROUP',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','PHANTOM FIN',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LRI',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LRU',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LRU IN A SUBCONTRACTED CA',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','LRU IN MASTER FIN',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','FIN IN PRIMARY',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','MASTER FIN',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','MULTIPLE QUANTITY FIN',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','PRIMARY',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','RCCB',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','SSPC',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','STANDARD ITEM',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','SW CERTIF UPLOADED BY AIRBUS',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','SW CERTIF UPLOADED BY EXTERN',null)
INSERT INTO t_choicelist (choicelist,choicevalue,choiceorder) VALUES ('FINCategory','SW APP UPLOADED BY AIRBUS CERT',null)