DELETE FROM
	T_PERMISSION_ACCESS_ATTRIBUTE 
WHERE 
	T_PERMISSION_ACCESS_ATTRIBUTE.idr_user_role = (SELECT T_USER_ROLE.id_role FROM T_USER_ROLE WHERE name_role = 'MAFU_AISS_READER')

DELETE FROM
	T_PERMISSION_ACCESS_ATTRIBUTE 
WHERE 
	T_PERMISSION_ACCESS_ATTRIBUTE.idr_user_role = (SELECT T_USER_ROLE.id_role FROM T_USER_ROLE WHERE name_role = 'MAFU_AISS_WRITER')
					 
if(exists(select * from T_USER_ROLE where name_role = 'MAFU_AISS_READER'))
begin
	DELETE FROM T_USER_ROLE WHERE name_role = 'MAFU_AISS_READER'
end		
			 
if(exists(select * from T_USER_ROLE where name_role = 'MAFU_AISS_WRITER'))
begin
	DELETE FROM T_USER_ROLE WHERE name_role = 'MAFU_AISS_WRITER'
end