if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[V_RFC]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[V_RFC]
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.V_RFC
AS
SELECT     
   	id_request AS id_rfc, 
   	ACMTLeaderCR AS rfc_ACMTLeaderCR,
	ChgLeaderCR AS rfc_ChgLeaderCR,
	CMITLeader AS rfc_CMITLeader,
  	EVCRLTaDateF AS rfc_EVCRLTaDateF,
	EVCRLTaDateT AS rfc_EVCRLTaDateT,
	EVCRLTiTDateA AS rfc_EVCRLTiTDateA,
   	EVCRTRSaDateF AS rfc_EVCRTRSaDateF,
	EVCRTRSaDateT AS rfc_EVCRTRSaDateT,
	EVCRTRSiTDateA AS rfc_EVCRTRSiTDateA,
    GIEqImpacted AS rfc_GIEqImpacted,
	GIRespSite AS rfc_GIRespSite,
	GrpLeaderCR AS rfc_GrpLeaderCR,
	ImpactOnBrakets AS rfc_ImpactOnBrakets,
   	INVModBDateA AS rfc_INVModBDateA,
	INVModBDateAv AS rfc_INVModBDateAv,
	INVModBDateT AS rfc_INVModBDateT,
	Linvold AS rfc_Linvold,
   	PDDesign AS rfc_PDDesign,
	PDImpact AS rfc_PDImpact,
	PDReference AS rfc_PDReference,
	RequestComment AS rfc_RequestComment,
	RequestReference AS rfc_RequestReference,
	RequestTitle AS rfc_RequestTitle,
	RFCCovered AS rfc_RFCCovered,
	RFCEpacTdu AS rfc_RFCEpacTdu,
	RFCStatus AS rfc_RFCStatus,
	RFCType AS rfc_RFCType,
	ScreenDate AS rfc_ScreenDate,
	StructureImpact AS rfc_StructureImpact,
	StudyReq AS rfc_StudyReq,
	TechLeader AS rfc_TechLeader,
	WFStatus AS rfc_WFStatus,
	WireImpactWMorpho AS rfc_WireImpactWMorpho,
	WireImpactWoMorphoImpact AS rfc_WireImpactWoMorphoImpact,
	GIGenComments AS rfc_GIGenComments,
	KickOffMeeting AS rfc_KickOffMeeting,
	UProcCR AS rfc_UProc,
	Request_ATA AS rfc_ATA,
	MODBreakdown AS rfc_MODBreakdown,
	ForecastDate AS rfc_ForecastDate,
	EngineeringComment AS rfc_EngineeringComment,
	ImplementationInFAL AS rfc_ImplementationInFAL,
	HarenessTr AS rfc_HarenessTr,
	PDAvailabilityDate AS rfc_PDAvailabilityDate,
	CircuitImpacted AS rfc_CircuitImpacted,
	NbOfPD AS rfc_NbOfPD,
	Rationale AS rfc_Rationale,
	BNDYEReviewDate AS rfc_BNDYEReviewDate,
	Cluster AS rfc_Cluster,
	OSTeamComment AS rfc_OSTeamComment,
	idr_ata AS rfc_idr_ata,
	PDAchievedDate AS rfc_PDAchievedDate,
	FullCoverDateT AS rfc_FullCoverDateT,
	XRefConfirmed,
	LaunchingDate,
	SYSCCC0ReleasedDate,
	IndustrialLeaderPosition AS rfc_IndustrialLeaderPosition,
	typeOfRequest AS rfc_typeOfRequest,
	Request_TickBox_idr AS rfc_Request_TickBox_idr,
	IESAttachment2 AS rfc_IESAttachment2 ,
	IESAttachment1 AS rfc_IESAttachment1 ,
	IESstatus AS rfc_IESstatus ,
	IESissue AS rfc_IESissue ,
	IESdate AS rfc_IESdate ,
	IESaccordingTo AS rfc_IESaccordingTo ,
	IESindusLeader AS rfc_IESindusLeader ,
	IESriskConfidence AS rfc_IESriskConfidence ,
	IESindusPosition AS rfc_IESindusPosition ,
	IEScustoDecisionDate AS rfc_IEScustoDecisionDate ,
	IESosw AS rfc_IESosw ,
	IESprsNeeded AS rfc_IESprsNeeded ,
	IESconditions AS rfc_IESconditions ,
	IESfleetWithOSW AS rfc_IESfleetWithOSW ,
	IESmsnWithOSW AS rfc_IESmsnWithOSW ,
	IESfleetWithoutOSW AS rfc_IESfleetWithoutOSW ,
	IESmsnWithoutOSW AS rfc_IESmsnWithoutOSW ,
	IESembodyOnAC AS rfc_IESembodyOnAC ,
	IESCDFpassed AS rfc_IESCDFpassed ,
	IESxRefComment AS rfc_IESxRefComment ,
	IES1stBuild AS rfc_IES1stBuild ,
	IESproposedCDF AS rfc_IESproposedCDF,
	rfcSoftDataLoading AS rfc_rfcSoftDataLoading,
	rfcRackEquipment AS rfc_rfcRackEquipment,
	rfcNonRackEquipment AS rfc_rfcNonRackEquipment,
	RFCacmtOrigin AS rfc_RFCacmtOrigin,
	cr_acIcdImpact AS rfc_cr_acIcdImpact, 
	cr_xmlFmdImpact AS rfc_cr_xmlFmdImpact, 
	cr_cbRccbSspcImpact AS rfc_cr_cbRccbSspcImpact, 
	cr_sb AS rfc_cr_sb, 
	cr_Ata42Impact AS rfc_cr_Ata42Impact, 
	cr_AtqcImpact AS rfc_cr_AtqcImpact, 
	cr_dsaRequired AS rfc_cr_dsaRequired, 
	cr_dmuIpact AS rfc_cr_dmuIpact, 
	WPLeaderCode AS rfc_WPLeaderCode, 
	JCRImpacted AS rfc_JCRImpacted, 
	SIRDand3DLayout AS rfc_SIRDand3DLayout, 
	EIRDand3DModelImpacted AS rfc_EIRDand3DModelImpacted, 
	SWRDandFDImpacted AS rfc_SWRDandFDImpacted, 
	ATA24ELAImpacted AS rfc_ATA24ELAImpacted, 
	WeightImpacted AS rfc_WeightImpacted, 
	TestsImpacted AS rfc_TestsImpacted, 
	LabTestsMeansImpacted AS rfc_LabTestsMeansImpacted, 
	LaunchingDateText AS rfc_LaunchingDateText, 
	SYSCCC0ReleasedDateText AS rfc_SYSCCC0ReleasedDateText,
	TypeRFC AS rfc_TypeRFC -- RFC type attribute
FROM		 dbo.T_REQUEST
WHERE	 (typeOfRequest = 'RFC')

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
