
UPDATE T_FEATURE SET where_clause='' WHERE label='Home' AND linked_url=' '
UPDATE T_FEATURE SET where_clause='' WHERE label='Reports' AND linked_url='Reports_templates/RT_display.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Search' AND linked_url='TOOL_OBJECTS/SEARCH/DESIGN/SEARCH_Design_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Save Search' AND linked_url='TOOL_OBJECTS/SEARCH/creation/SEARCH_Creation_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Last Search' AND linked_url='TOOL_OBJECTS/SEARCH/DISPLAYRESULT/SEARCH_DisplayResult_Form.php?profil_label=LAST_SEARCH'
UPDATE T_FEATURE SET where_clause='SELECT id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND (last_effective = 1 OR (last_effective=0 AND ds_type = 0))' WHERE label='Create SI' AND linked_url='BUSINESS_OBJECTS/DS/CREATION/DS_CreationFromOrigin_getData.php?id_ds_origin=#id_ds#&id_fin=#id_fin#&type_DS=1'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create Lab DS' AND linked_url='BUSINESS_OBJECTS/DS/CREATION/DS_CreationFromOrigin_getData.php?id_ds_origin=#id_ds#&id_fin=#id_fin#&type_DS=2'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and (SystemViewStatus = ''WIP'' or SystemViewStatus = ''HELD'' or SystemViewStatus = ''TO BE REFURBISHED'')' WHERE label='Edit' AND linked_url='BUSINESS_OBJECTS/DS/update/DS_Update_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=2' WHERE label='Delete' AND linked_url='BUSINESS_OBJECTS/DS/LAB_DS/DELETION/LAB_DS_Deletion_Process.php?id_ds=#id_ds#&id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=1 and SystemViewStatus = ''RELEASED''' WHERE label='Refurbish SI' AND linked_url='BUSINESS_OBJECTS/DS/SI/refurbish/SI_Refurbish_Form.php?id_si=#id_ds#&id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=1 and SystemViewStatus = ''WIP''' WHERE label='Delete' AND linked_url='BUSINESS_OBJECTS/DS/SI/DELETION/SI_Deletion_Process.php?id_si=#id_ds#&id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=1 and (SystemViewStatus = ''WIP'' or SystemViewStatus = ''HELD'')' WHERE label='Unlink Equipment' AND linked_url='BUSINESS_OBJECTS/DS/UNLINK/DS_UnlinkEquipment_Process.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=DS&id=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='BUSINESS_OBJECTS/DS/UPDATE/update.php?view=supp&type=supp§ion=supplier&id_supplier=#id_supplier#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete' AND linked_url=''
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=SUPP&id=#id_supplier#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='BUSINESS_OBJECTS/EQPT/UPDATE/EQPT_Update_Form.php?id_equip=#id_equip#'
UPDATE T_FEATURE SET where_clause='select idr_supplier FROM R_EQUIPMENT WHERE id_equip=#id_equip# ' WHERE label='Unlink Supplier' AND linked_url='BUSINESS_OBJECTS/EQPT/UNLINK/EQPT_UnlinkSupplier_Process.php?id_equip=#id_equip#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='BUSINESS_OBJECTS/CI/UPDATE/CI_Update_Form.php?id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=CI&id=#id_fin#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create PD DS' AND linked_url='BUSINESS_OBJECTS/PDDS/creation/PDDS_Creation_Form.php?id_pdci=#id_pdci#'
UPDATE T_FEATURE SET where_clause='select id_pdds FROM T_PDDS WHERE id_pdds=#id_pdds# and pdds_status <> ''VALIDATED BY SCREENING COMMITTEE''' WHERE label='Edit' AND linked_url='BUSINESS_OBJECTS/PDDS/update/PDDS_Update_Form.php?id_pdds=#id_pdds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create PD CI' AND linked_url='BUSINESS_OBJECTS/PDCI/creation/PDCI_Creation_Form.php?id_ata=#id_ata#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Release PD DS' AND linked_url='BUSINESS_OBJECTS/PDDS/update/PDDS_Update_Released_Process.php?id_pdds=#id_pdds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=PDDS&id=#id_pdds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=PDCI&id=#id_pdci#'
UPDATE T_FEATURE SET where_clause='SELECT select_clause FROM T_SEARCH_PROFIL WHERE label = ''#profil_label#'' AND idr_user = #current_user#' WHERE label='Export' AND linked_url='TOOL_OBJECTS/SEARCH/export/SEARCH_export.php?profil_label=#profil_label#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=1' WHERE label='Report SI' AND linked_url='BUSINESS_OBJECTS/DS/SI/consult/SI_Consultation_PDF_Process.php?id_si=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Load Saved Profile' AND linked_url='TOOL_OBJECTS/SEARCH/open/SEARCH_Open_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='TOOL_OBJECTS/ROLE/UPDATE/ROLE_Update_Form.php?id_role=#id_role#'
UPDATE T_FEATURE SET where_clause='' WHERE label='New User' AND linked_url='USER/create/USER_Create_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='USER/update/USER_Update_Form.php?id_user=#id_user#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete User' AND linked_url='USER/delete/USER_Delete_Form.php?id_user=#id_user#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Init Password' AND linked_url='USER/update/USER_initPass_Process.php?id_user=#id_user#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Manage Role' AND linked_url='TOOL_OBJECTS/ROLE/ROLE_index.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Manage User' AND linked_url='/USER/USER_index.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Manage PCD' AND linked_url='/BUSINESS_OBJECTS/CI/UPDATE/CI_LinkFINManyToMany_Form.php?id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='' WHERE label='New Role' AND linked_url='TOOL_OBJECTS/ROLE/create/ROLE_Create_Form.php'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND ( idr_equip='''' OR idr_equip IS NULL) ' WHERE label='Link Equipment' AND linked_url='BUSINESS_OBJECTS/DS/link/DS_linkEquipment_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type<>1 and (idr_mp IS NOT NULL OR idr_mp <> '''')' WHERE label='Unlink MP' AND linked_url='BUSINESS_OBJECTS/DS/UNLINK/DS_UnlinkMP_Process.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create CR' AND linked_url='BUSINESS_OBJECTS/CR/create/CR_Creation_Form.php'
UPDATE T_FEATURE SET where_clause='select id_equip FROM R_EQUIPMENT WHERE id_equip=#id_equip# AND (idr_supplier='''' OR idr_supplier IS NULL) ' WHERE label='Link Supplier' AND linked_url='BUSINESS_OBJECTS/EQPT/link/EQPT_linkSupplier_Form.php?id_equip=#id_equip#'
UPDATE T_FEATURE SET where_clause='select null' WHERE label='Link MP' AND linked_url='BUSINESS_OBJECTS/DS/link/DS_linkMP_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/CR/update/CR_Evaluation_Update_Form.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/CR/update/CR_Investigation_Update_Form.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/CR/update/CR_Implementation_Update_Form.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/MEETING/update/Meeting_Update_Form.php?id_meeting=#id_meeting#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Meeting' AND linked_url='/BUSINESS_OBJECTS/MEETING/create/Meeting_Create_Form.php?id_req=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Meeting' AND linked_url='/BUSINESS_OBJECTS/MEETING/create/Meeting_Create_Form.php?id_req=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create RFC' AND linked_url='BUSINESS_OBJECTS/RFC/create/RFC_Creation_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/CR/update/CR_Update_Form.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link MP' AND linked_url='/BUSINESS_OBJECTS/REQUEST/LINK/Link_Req_To_Cin_From.php?id_req=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link Request' AND linked_url='/BUSINESS_OBJECTS/MP/LINK/Link_CIN_To_Req_From.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link MP' AND linked_url='/BUSINESS_OBJECTS/REQUEST/LINK/Link_Req_To_Cin_From.php?id_req=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/RFC/update/RFC_Update_Form.php?id_rfc=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link ATA' AND linked_url='/BUSINESS_OBJECTS/MP/LINK/Link_MP_To_ATA_From.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/MP/update/MP_Update_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Impact PD' AND linked_url='/BUSINESS_OBJECTS/PDCI/link/PDCI_LinkMP_Form.php?id_pdci=#id_pdci#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link Requirement' AND linked_url='/BUSINESS_OBJECTS/PDDS/link/PDDS_LinkRequirement_Form.php?id_pdds=#id_pdds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create MP' AND linked_url='/BUSINESS_OBJECTS/MP/create/MP_Creation_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/MOD/update/MOD_Update_Form.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/ACTION/update/Action_Update_Form.php?id_action=#id_action#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Action' AND linked_url='/BUSINESS_OBJECTS/ACTION/create/Action_Creation_Form.php?id_request=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Action' AND linked_url='/BUSINESS_OBJECTS/ACTION/create/Action_Creation_Form.php?id_request=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link MOD' AND linked_url='/BUSINESS_OBJECTS/MP/LINK/Link_MOD_To_MP_From.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link MP' AND linked_url='/BUSINESS_OBJECTS/MOD/LINK/Link_MP_To_MOD_From.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='SELECT id_mp, MPReference AS Title FROM T_MP INNER JOIN T_LINK_MOD_MP ON T_MP.id_mp = T_LINK_MOD_MP.idr_mp WHERE id_mp=#id_mp#' WHERE label='Unlink MOD' AND linked_url='/BUSINESS_OBJECTS/MP/UNLINK/Unlink_MOD_To_MP_From.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='SELECT id_mp, MPReference AS Title FROM T_MP INNER JOIN T_LINK_MOD_MP ON T_MP.id_mp = T_LINK_MOD_MP.idr_mp WHERE T_LINK_MOD_MP.idr_mod=#id_mod#' WHERE label='Unlink MP' AND linked_url='/BUSINESS_OBJECTS/MOD/UNLINK/Unlink_MP_To_MOD_From.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Search' AND linked_url='TOOL_OBJECTS/SEARCH/EDIT/SEARCH_Edit_Form.php?profil_label=LAST_SEARCH¤t_page=#current_page#&renamed_order_attr=#renamed_order_attr#&sort_direction=#sort_direction#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link ATA' AND linked_url='/BUSINESS_OBJECTS/REQUEST/LINK/Link_Req_To_ATA_From.php?id_req=#id_cr#'
UPDATE T_FEATURE SET where_clause='SELECT id_request FROM T_REQUEST WHERE id_request=#id_cr# AND idr_ata IS NOT NULL' WHERE label='Unlink ATA' AND linked_url='/BUSINESS_OBJECTS/REQUEST/UNLINK/Unlink_Req_To_ATA_Process.php?id_req=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link ATA' AND linked_url='/BUSINESS_OBJECTS/REQUEST/LINK/Link_Req_To_ATA_From.php?id_req=#id_rfc#'
UPDATE T_FEATURE SET where_clause='SELECT id_request FROM T_REQUEST WHERE id_request=#id_rfc# AND idr_ata IS NOT NULL' WHERE label='Unlink ATA' AND linked_url='/BUSINESS_OBJECTS/REQUEST/UNLINK/Unlink_Req_To_ATA_Process.php?id_req=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Link ATA' AND linked_url='/BUSINESS_OBJECTS/MOD/LINK/Link_ATA_To_MOD_From.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='SELECT id_mod FROM T_MOD WHERE id_mod=#id_mod# AND idr_mod_ata IS NOT NULL' WHERE label='Unlink ATA' AND linked_url='/BUSINESS_OBJECTS/MOD/UNLINK/Unlink_MOD_To_ATA_Process.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Action' AND linked_url='/BUSINESS_OBJECTS/ACTION/create/Action_Creation_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Action' AND linked_url='/BUSINESS_OBJECTS/ACTION/create/Action_Creation_Form.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Meeting' AND linked_url='/BUSINESS_OBJECTS/MEETING/create/Meeting_Create_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add Meeting' AND linked_url='/BUSINESS_OBJECTS/MEETING/create/Meeting_Create_Form.php?id_mod=#id_mod#'
UPDATE T_FEATURE SET where_clause='SELECT id_mp FROM T_MP WHERE id_mp=#id_mp# AND idr_ata IS NOT NULL' WHERE label='Unlink ATA' AND linked_url='/BUSINESS_OBJECTS/MP/UNLINK/Unlink_MP_To_ATA_Process.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit TRS inv. teams' AND linked_url='/BUSINESS_OBJECTS/MP/update/MP_Update_IT_Form.php?deliv=Deliverable%20TRS&id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit TRS of RFC inv. teams' AND linked_url='/BUSINESS_OBJECTS/RFC/Update/RFC_Update_IT_Form.php?deliv=TRS%20of%20RFC&id_rfc=#id_rfc#'
UPDATE T_FEATURE SET where_clause='SELECT id_request FROM T_MP INNER JOIN T_LINK_REQUEST_MP ON id_mp=idr_mp INNER JOIN T_REQUEST ON id_request=idr_request WHERE id_mp =#id_mp#' WHERE label='Unlink Request' AND linked_url='/BUSINESS_OBJECTS/MP/UNLINK/Unlink_Request_To_MP_From.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='SELECT id_mp FROM T_MP INNER JOIN T_LINK_REQUEST_MP ON id_mp=idr_mp INNER JOIN T_REQUEST ON id_request=idr_request WHERE id_request =#id_cr#' WHERE label='Unlink MP' AND linked_url='/BUSINESS_OBJECTS/REQUEST/UNLINK/Unlink_Request_To_MP_From.php?id_req=#id_cr#'
UPDATE T_FEATURE SET where_clause='SELECT id_mp FROM T_MP INNER JOIN T_LINK_REQUEST_MP ON id_mp=idr_mp INNER JOIN T_REQUEST ON id_request=idr_request WHERE id_request =#id_rfc#' WHERE label='Unlink MP' AND linked_url='/BUSINESS_OBJECTS/REQUEST/UNLINK/Unlink_Request_To_MP_From.php?id_req=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit ES inv. teams' AND linked_url='/BUSINESS_OBJECTS/CR/Update/CR_Update_IT_Form.php?deliv=Deliverable%20ES&id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Export files' AND linked_url='TOOL_OBJECTS/SEARCH/export/Bat_export.php?filename=PD.bat'
UPDATE T_FEATURE SET where_clause='' WHERE label='Validate TRS Check List' AND linked_url='/BUSINESS_OBJECTS/MP/checklist/TRS_Checklist_form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='SELECT * FROM OPENCIN WHERE CheckCIN=0' WHERE label='Validate new CIN' AND linked_url='/BUSINESS_OBJECTS/CIN/check_new/check_new_cin_form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete' AND linked_url='/BUSINESS_OBJECTS/ACTION/delete/Action_Delete_Form.php?id_action=#id_action#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete' AND linked_url='/BUSINESS_OBJECTS/MEETING/delete/Meeting_Delete_Form.php?id_meeting=#id_meeting#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete' AND linked_url='/BUSINESS_OBJECTS/CR/delete/CR_Delete_Form.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete' AND linked_url='/BUSINESS_OBJECTS/RFC/delete/RFC_Delete_Form.php?id_rfc=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Lead Time inv. teams' AND linked_url='/BUSINESS_OBJECTS/RFC/Update/RFC_Update_IT_Form.php?deliv=Lead%20Time&id_rfc=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Consult PRS' AND linked_url='/BUSINESS_OBJECTS/PRS/consult/PRS_Consultation_Form.php?id_prs=#id_prs#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit PRS' AND linked_url='/BUSINESS_OBJECTS/PRS/Update/PRS_Update_Form.php?id_prs=#id_prs#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Export PRS' AND linked_url='/BUSINESS_OBJECTS/PRS/export/PRS_Export.php?id_prs=#id_prs#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete MP' AND linked_url='/BUSINESS_OBJECTS/MP/delete/MP_Delete_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE ( id_ds=#id_ds#) AND (DIActive = ''yes'')' WHERE label='Truth Table' AND linked_url='BUSINESS_OBJECTS/DS/consult/DS_Consultation_Truth_Table_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Consult Tick Box' AND linked_url='BUSINESS_OBJECTS/Tick_Box/consult/TickBox_Consultation_Form.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add this MP to Tick Box' AND linked_url='/BUSINESS_OBJECTS/Tick_Box/LINK/Link_TickBox_Form.php?id_reference=#id_mp#&typeOfRequest=MP'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add this CR to Tick Box' AND linked_url='/BUSINESS_OBJECTS/Tick_Box/LINK/Link_TickBox_Form.php?id_reference=#id_cr#&typeOfRequest=CR'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add this RFC to Tick Box' AND linked_url='/BUSINESS_OBJECTS/Tick_Box/LINK/Link_TickBox_Form.php?id_reference=#id_rfc#&typeOfRequest=RFC'
UPDATE T_FEATURE SET where_clause='SELECT id_si FROM T_SI WHERE (id_si = #id_si#) AND (LifeCycleState <> ''WIP'')' WHERE label='EditTLB' AND linked_url='BUSINESS_OBJECTS/DS/SI/update/SI_Update_Form.php?id_si=#id_si#'
UPDATE T_FEATURE SET where_clause='select id_cr FROM V_CR WHERE (cr_Prerequisite_File is null or cr_Prerequisite_File ='''') AND id_cr=#id_cr#' WHERE label='Generate prerequisite file' AND linked_url='/BUSINESS_OBJECTS/CR/consult/CR_prerequisite.php?id_cr=#id_cr#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE (ds_type=4)' WHERE label='Copy from another EDD' AND linked_url='/BUSINESS_OBJECTS/DS/EDD/Duplicate/TRUTH_TABLE/EDD_TruthTable_Duplicate_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create EDD' AND linked_url='BUSINESS_OBJECTS/DS/EDD/creation/EDD_Creation_Form.php'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=4 and ((MG = ''1'') OR (MG IS NULL) OR (MG = ''0''))' WHERE label='Delete EDD' AND linked_url='BUSINESS_OBJECTS/DS/EDD/DELETE/EDD_Deletion_Process.php?id_ds=#id_ds#&id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE ( id_ds=#id_ds#) and (MG = 1 OR MG = 2) and (ds_type=4)' WHERE label='Downgrade to lower MG' AND linked_url='/BUSINESS_OBJECTS/DS/EDD/MG/Lower_MG_Process.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT R_FIN_DS.id_ds FROM R_FIN_DS WHERE R_FIN_DS.id_ds = #id_ds# AND ds_type=4 AND R_FIN_DS.MG < 2 AND R_FIN_DS.id_ds NOT IN ( SELECT T_IMPACTDS.idr_ds_pre FROM T_IMPACTDS WHERE T_IMPACTDS.idr_ds_pre = #id_ds# )' WHERE label='EDD Link FIN CI' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Link/Link_FIN_CI/EDD_linkFINCI_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS INNER JOIN R_FIN_CI ON R_FIN_DS.idr_fin = R_FIN_CI.id_fin WHERE id_ds=#id_ds# AND MG < 2 AND ds_type=4 AND fin_ds_sv IS NULL' WHERE label='EDD Link MP' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Link/Link_MP/EDD_linkMP_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND ds_type=4 AND MG > 1' WHERE label='EDD Link PDCI' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Link/LINK_PDCI/EDD_LinkPDCI_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT T_MP.id_mp FROM R_FIN_DS INNER JOIN T_IMPACTDS ON R_FIN_DS.id_ds = T_IMPACTDS.idr_ds_post INNER JOIN T_MP ON T_IMPACTDS.idr_mp = T_MP.id_mp WHERE T_IMPACTDS.idr_ds_post = #id_ds# AND MG < 2 AND ds_type=4 AND fin_ds_sv IS NULL' WHERE label='EDD Unlink MP' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Unlink/Unlink_MP/Unlink_MP_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT id_ds FROM R_FIN_DS WHERE (id_ds = #id_ds#) AND (idr_pdci IS NOT NULL OR idr_pdci > 0)' WHERE label='EDD Unlink PDCI' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Unlink/Unlink_PDCI/Unlink_PDCI_Process.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT R_FIN_DS.id_ds FROM R_FIN_DS LEFT OUTER JOIN T_IMPACTDS ON T_IMPACTDS.idr_ds_post = R_FIN_DS.id_ds LEFT OUTER JOIN T_MP ON T_MP.id_mp = T_IMPACTDS.idr_mp LEFT OUTER JOIN T_LINK_MOD_MP ON T_LINK_MOD_MP.idr_mp = T_MP.id_mp WHERE (R_FIN_DS.id_ds = #id_ds#) AND (R_FIN_DS.ds_type = 4) AND (R_FIN_DS.MG < 3)' WHERE label='Edit EDD' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Update/EDD_Update_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit ELA' AND linked_url='/BUSINESS_OBJECTS/DS/ELA/update/ELA_Update_Form.php?id_ELA=#id_ELA#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit MSN Power Center' AND linked_url='/BUSINESS_OBJECTS/MSNPOWERCENTER/update/MSNPOWERCENTER_Update_Form.php?id_msnpc=#id_msnpc#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND MG < 3 AND ds_type=4' WHERE label='Edit Truth Table inputs' AND linked_url='BUSINESS_OBJECTS/DS/update/DS_Update_VLs_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND MG < 3 AND ds_type=4' WHERE label='Edit Truth Table outputs' AND linked_url='BUSINESS_OBJECTS/DS/update/DS_Update_Truth_Table_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# AND ds_type=4' WHERE label='ELA' AND linked_url='/BUSINESS_OBJECTS/DS/ELA/consult/ELA_Consultation_Form.php?id_ELA=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE (id_ds=#id_ds#) and (MG<3) and (ds_type=4)' WHERE label='Upgrade to uppper MG' AND linked_url='/BUSINESS_OBJECTS/DS/EDD/MG/Upper_MG_Process.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit' AND linked_url='/BUSINESS_OBJECTS/QUALITY_CHECK/update/QCheck_Update_Form.php?id_qc=#id_qc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Copy from' AND linked_url='/BUSINESS_OBJECTS/QUALITY_CHECK/update/QCheck_Copy_Form.php?id_qc=#id_qc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='MOD History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=MOD&id=#id_mod#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Print EDD' AND linked_url='BUSINESS_OBJECTS/DS/consult/EDD_Print.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE (ds_type=4)' WHERE label='Save as new EDD' AND linked_url='/BUSINESS_OBJECTS/DS/EDD/Duplicate/TRUTH_TABLE/EDD_DuplicateAsNew_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='select id_ds FROM R_FIN_DS WHERE id_ds=#id_ds# and ds_type=1 and SystemViewStatus = ''RELEASED''' WHERE label='Cancel SI' AND linked_url='BUSINESS_OBJECTS/DS/SI/cancel/SI_Cancel_Form.php?id_si=#id_ds#&id_fin=#id_fin#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Check Deliverable' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/update/Check_Deliverable_Update_Form.php?id_checkDeliverable=#id_checkDeliverable#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create Check Deliverable' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/create/Check_Deliverable_create_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add a LNDYOCS Workflow' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/WORKFLOW/create/workflow_create_Process.php?id_checkDeliverable=#id_checkDeliverable#&typeOfWorkflow=LNDYOCS'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add a Head of Conf. Workflow' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/WORKFLOW/create/workflow_create_Process.php?id_checkDeliverable=#id_checkDeliverable#&typeOfWorkflow=Conf'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add a Head of Engineering Workflow' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/WORKFLOW/create/workflow_create_Process.php?id_checkDeliverable=#id_checkDeliverable#&typeOfWorkflow=Engineering'
UPDATE T_FEATURE SET where_clause='' WHERE label='Add a Head of Certif.Workflow' AND linked_url='BUSINESS_OBJECTS/CHECK_DELIVERABLE/WORKFLOW/create/workflow_create_Process.php?id_checkDeliverable=#id_checkDeliverable#&typeOfWorkflow=Certif'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create Delta 1' AND linked_url='BUSINESS_OBJECTS/DELTA1/create/Delta1_create_Process.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Delta 1' AND linked_url='BUSINESS_OBJECTS/DELTA1/update/Delta1_Update_Form.php?id_delta1=#id_delta1#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete Delta 1' AND linked_url='BUSINESS_OBJECTS/DELTA1/delete/Delta1_Delete_Process.php?id_delta1=#id_delta1#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create Delta 0' AND linked_url='BUSINESS_OBJECTS/DELTA0/create/Delta0_create_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Delta 0' AND linked_url='BUSINESS_OBJECTS/DELTA0/update/Delta0_Update_Form.php?id_delta0=#id_delta0#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete Delta 0' AND linked_url='BUSINESS_OBJECTS/DELTA0/delete/Delta0_Delete_Process.php?id_delta0=#id_delta0#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit Mod Closure' AND linked_url='BUSINESS_OBJECTS/MOD_CLOSURE/update/Stage_Update_Form.php?id_stage=#id_stage#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Create Mod Closure' AND linked_url='BUSINESS_OBJECTS/MOD_CLOSURE/create/Stage_create_Form.php?id_mp=#id_mp#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Delete Mod Closure' AND linked_url='BUSINESS_OBJECTS/MOD_CLOSURE/delete/Stage_Delete_Process.php?id_stage=#id_stage#'
UPDATE T_FEATURE SET where_clause='' WHERE label='History' AND linked_url='TOOL_OBJECTS/HISTORY/HISTORY_onObject.php?object=EQUIPEMENT&id=#id_equip#'
UPDATE T_FEATURE SET where_clause='SELECT R_FIN_DS.id_ds FROM R_FIN_DS WHERE R_FIN_DS.id_ds = #id_ds# AND ds_type=4 AND R_FIN_DS.MG =3' WHERE label='Edit after MG3' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Update/EDD_Update_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Edit SB' AND linked_url='BUSINESS_OBJECTS/SB/update/SB_Update_Form.php?id_SB=#id_SB#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Export IES' AND linked_url='BUSINESS_OBJECTS/RFC/consult/RFC_export_IES.php?id_rfc=#id_rfc#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Print All EDD' AND linked_url='BUSINESS_OBJECTS/DS/consult/EDD_PrintAll.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='SELECT R_FIN_DS.id_ds FROM R_FIN_DS WHERE R_fin_ds.idr_fin is not null AND R_FIN_DS.fin_ds_sv is null AND R_FIN_DS.id_ds = #id_ds# AND ds_type=4 AND R_FIN_DS.MG < 2 AND R_FIN_DS.id_ds NOT IN ( SELECT T_IMPACTDS.idr_ds_pre FROM T_IMPACTDS WHERE T_IMPACTDS.idr_ds_pre = #id_ds#)' WHERE label='EDD Unlink FIN CI' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Unlink/Unlink_FIN_CI/Unlink_FINCI_Form.php?id_ds=#id_ds#'
UPDATE T_FEATURE SET where_clause='' WHERE label='Migration A400M' AND linked_url='BUSINESS_OBJECTS/DS/EDD/Migration/Check_data.php'
UPDATE T_FEATURE SET where_clause='' WHERE label='Impact ACMT or CoE' AND linked_url='BUSINESS_OBJECTS/MP/update/MP_Update_ACMTinvolvement_Form.php?deliv=IT&id_mp=#id_mp#'