BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Tmp_OPENCIN
	(
	MOD varchar(6) NOT NULL,
	MP varchar(7) NOT NULL,
	OpenDate datetime NULL,
	CheckCIN bit NULL
	)  ON [PRIMARY]
GO
IF EXISTS(SELECT * FROM dbo.OPENCIN)
	 EXEC('INSERT INTO dbo.Tmp_OPENCIN (MOD, MP, OpenDate, CheckCIN)
		SELECT MOD, MP, OpenDate, CheckCIN FROM dbo.OPENCIN TABLOCKX')
GO
DROP TABLE dbo.OPENCIN
GO
EXECUTE sp_rename N'dbo.Tmp_OPENCIN', N'OPENCIN', 'OBJECT'
GO
COMMIT
