BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Tmp_T_CIN
	(
	id_cin int NOT NULL IDENTITY (1, 1),
	MODNUMBER varchar(6) NOT NULL,
	MPNUMBER varchar(7) NOT NULL,
	MODTITLE varchar(200) NULL,
	MPTITLE varchar(200) NULL,
	STATESTATE varchar(200) NULL
	)  ON [PRIMARY]
GO
SET IDENTITY_INSERT dbo.Tmp_T_CIN ON
GO
IF EXISTS(SELECT * FROM dbo.T_CIN)
	 EXEC('INSERT INTO dbo.Tmp_T_CIN (id_cin, MODNUMBER, MPNUMBER, MODTITLE, MPTITLE, STATESTATE)
		SELECT id_cin, MODNUMBER, MPNUMBER, MODTITLE, MPTITLE, STATESTATE FROM dbo.T_CIN TABLOCKX')
GO
SET IDENTITY_INSERT dbo.Tmp_T_CIN OFF
GO
DROP TABLE dbo.T_CIN
GO
EXECUTE sp_rename N'dbo.Tmp_T_CIN', N'T_CIN', 'OBJECT'
GO
ALTER TABLE dbo.T_CIN ADD CONSTRAINT
	PK_T_CIN PRIMARY KEY CLUSTERED 
	(
	id_cin
	) WITH FILLFACTOR = 90 ON [PRIMARY]

GO
COMMIT
