-- A380_Admin_data context ID and all domain insertion


DECLARE @CONTEXT_id_old INT

SELECT @CONTEXT_id_old = CONTEXT_id FROM T_EDIP_CONTEXT WHERE ContextName='A380_Admin_data'



IF NOT EXISTS(SELECT * FROM T_LINK_CONTEXT__DOMAIN WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id_old )
BEGIN
INSERT INTO T_LINK_CONTEXT__DOMAIN (
CONTEXT__DOMAIN_CONTEXT_idr,
CONTEXT__DOMAIN_DOMAIN_idr,
ContextDomainReadMode,
ContextDomainWriteMode
) SELECT @CONTEXT_id_old, DOMAIN_id, 1, 1 FROM T_DOMAIN;
END
ELSE
BEGIN
UPDATE T_LINK_CONTEXT__DOMAIN SET ContextDomainReadMode = 1, ContextDomainWriteMode = 1 WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id_old;
END