-- rename feature Compiler signature
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Date' where AttributeName='WDDSSignCompiledVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote' where AttributeName='WDDSSignCompiledVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Name (after 05/2012) ' where AttributeName='WDDSSignCompiledName'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Date' where AttributeName='PDDSSignCompiledVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote' where AttributeName='PDDSSignCompiledVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Name (after 05/2012) ' where AttributeName='PDDSSignCompiledName'


-- rename feature Designer signature
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Name (before 05/2012) ' where AttributeName='WDDSSignDesignerName'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote' where AttributeName='WDDSSignDesignerVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Date' where AttributeName='WDDSSignDesignerVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Commentary' where AttributeName='WDDSSignDesignerVoteComm'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Name (before 05/2012) ' where AttributeName='PDDSSignDesignerName'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote' where AttributeName='PDDSSignDesignerVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Date' where AttributeName='PDDSSignDesignerVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Compiler Vote Commentary' where AttributeName='PDDSSignDesignerVoteComm'

-- rename feature Approver signature
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote Date' where AttributeName='WDDSSignCCVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote' where AttributeName='WDDSSignCCVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Name' where AttributeName='WDDSSignCCName'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote Commentary' where AttributeName='WDDSSignCCVoteComm'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote Date' where AttributeName='PDDSSignCCVoteDate'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote' where AttributeName='PDDSSignCCVote'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Name' where AttributeName='PDDSSignCCName'
update T_EDIP_ATTRIBUTE set AttributeLabel='Approver Vote Commentary' where AttributeName='PDDSSignCCVoteComm'

-- rename feature Checker signature
update T_EDIP_ATTRIBUTE set AttributeLabel='Checker Vote Commentary' where AttributeName='WDDSSignCheckerVoteComm'
update T_EDIP_ATTRIBUTE set AttributeLabel='Checker Vote Commentary' where AttributeName='PDDSSignCheckerVoteComm'

-- update vote for Compiler and Designer signatures
update T_EDIP_ATTRIBUTE set Valueslist='PENDING;APPROVED' where AttributeName='WDDSSignCompiledVote'
update T_EDIP_ATTRIBUTE set Valueslist='PENDING;APPROVED' where AttributeName='PDDSSignCompiledVote'
update T_EDIP_ATTRIBUTE set Valueslist='PENDING;SIGNED' where AttributeName='WDDSSignDesignerVote'
update T_EDIP_ATTRIBUTE set Valueslist='PENDING;SIGNED' where AttributeName='PDDSSignDesignerVote'

-- order group 17 (WDDS)
update T_EDIP_ATTRIBUTE set attributeorder='34' where attributename='WDDSSignDesignerVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='35' where attributename='WDDSSignDesignerVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='33' where attributename='WDDSSignDesignerName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='36' where attributename='WDDSSignDesignerVoteComm' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='40' where attributename='WDDSSignCheckerName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='41' where attributename='WDDSSignCheckerVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='42' where attributename='WDDSSignCheckerVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='43' where attributename='WDDSSignCheckerVoteComm' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='38' where attributename='WDDSSignCompiledVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='44' where attributename='WDDSSignCCName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='37' where attributename='WDDSSignCompiledName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='45' where attributename='WDDSSignCCVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='46' where attributename='WDDSSignCCVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='39' where attributename='WDDSSignCompiledVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='47' where attributename='WDDSSignCCVoteComm' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='48' where attributename='WDDSSignSRName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='49' where attributename='WDDSSignSRVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='50' where attributename='WDDSSignSRVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='51' where attributename='WDDSSignSRVoteComm' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='52' where attributename='WDDSSignSRCName' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='53' where attributename='WDDSSignSRCVote' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='54' where attributename='WDDSSignSRCVoteDate' and attribute_attribute_group_idr='17'
update T_EDIP_ATTRIBUTE set attributeorder='55' where attributename='WDDSSignSRCVoteComm' and attribute_attribute_group_idr='17'

-- order group (PDDS)
update T_EDIP_ATTRIBUTE set attributeorder='4' where attributename='PDDSSignDesignerVoteComm' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='2' where attributename='PDDSSignDesignerVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='3' where attributename='PDDSSignDesignerVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='1' where attributename='PDDSSignDesignerName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='7' where attributename='PDDSSignCompiledVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='6' where attributename='PDDSSignCompiledVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='5' where attributename='PDDSSignCompiledName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='8' where attributename='PDDSSignCheckerName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='9' where attributename='PDDSSignCheckerVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='10' where attributename='PDDSSignCheckerVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='11' where attributename='PDDSSignCheckerVoteComm' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='12' where attributename='PDDSSignCCName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='13' where attributename='PDDSSignCCVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='14' where attributename='PDDSSignCCVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='15' where attributename='PDDSSignCCVoteComm' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='16' where attributename='PDDSSignSRName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='17' where attributename='PDDSSignSRVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='18' where attributename='PDDSSignSRVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='19' where attributename='PDDSSignSRVoteComm' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='20' where attributename='PDDSSignSRCName' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='21' where attributename='PDDSSignSRCVote' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='22' where attributename='PDDSSignSRCVoteDate' and attribute_attribute_group_idr='16'
update T_EDIP_ATTRIBUTE set attributeorder='23' where attributename='PDDSSignSRCVoteComm' and attribute_attribute_group_idr='16'
