DECLARE @CONTEXT_id INT
DECLARE @DOMAIN_id INT

-- **** ADD NEW DOMAIN A400M_A-E_DO ****
IF
(
	NOT exists (select * from T_DOMAIN where DomainName = 'A400M_A-E_DO')
)
BEGIN
	--Insert domain
	INSERT INTO T_DOMAIN (DomainName, DomainRepository, DomainCirce) VALUES ('A400M_A-E_DO','A400M_A-E_DO','')
END

SELECT @DOMAIN_id = Domain_id FROM T_DOMAIN WHERE DomainName='A400M_A-E_DO'


-- **** CREATE ROLE A400M_WRITER_A-E_DO ****

IF(NOT EXISTS(SELECT * FROM T_EDIP_CONTEXT WHERE ContextName='A400M_Writer_A-E_DO'))
BEGIN
	INSERT INTO T_EDIP_CONTEXT (ContextName,ContextType,ContextPowerValue) VALUES ('A400M_Writer_A-E_DO',1,10)
END

SELECT @CONTEXT_id = CONTEXT_id FROM T_EDIP_CONTEXT WHERE ContextName='A400M_Writer_A-E_DO'


IF NOT EXISTS(SELECT * FROM T_LINK_CONTEXT__DOMAIN WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id  AND CONTEXT__DOMAIN_DOMAIN_idr=@DOMAIN_id)
BEGIN
INSERT INTO T_LINK_CONTEXT__DOMAIN (
CONTEXT__DOMAIN_CONTEXT_idr,
CONTEXT__DOMAIN_DOMAIN_idr,
ContextDomainReadMode,
ContextDomainWriteMode
) VALUES (@CONTEXT_id, @DOMAIN_id, 1, 1);
END
ELSE
BEGIN
UPDATE T_LINK_CONTEXT__DOMAIN SET ContextDomainReadMode = 1, ContextDomainWriteMode = 1 WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id AND CONTEXT__DOMAIN_DOMAIN_idr=@DOMAIN_id;
END

-- **** UPDATE ROLE A400M_VIEWER_DO ****

SELECT @CONTEXT_id = CONTEXT_id FROM T_EDIP_CONTEXT WHERE ContextName='A400M_Viewer_DO'


IF NOT EXISTS(SELECT * FROM T_LINK_CONTEXT__DOMAIN WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id AND CONTEXT__DOMAIN_DOMAIN_idr=@DOMAIN_id)
BEGIN
INSERT INTO T_LINK_CONTEXT__DOMAIN (
CONTEXT__DOMAIN_CONTEXT_idr,
CONTEXT__DOMAIN_DOMAIN_idr,
ContextDomainReadMode,
ContextDomainWriteMode
) VALUES (@CONTEXT_id, @DOMAIN_id, 1, 0);
END
ELSE
BEGIN
UPDATE T_LINK_CONTEXT__DOMAIN SET ContextDomainReadMode = 1, ContextDomainWriteMode = 0 WHERE CONTEXT__DOMAIN_CONTEXT_idr=@CONTEXT_id AND CONTEXT__DOMAIN_DOMAIN_idr=@DOMAIN_id;
END

-- **** ASSOCIATE ROLE A400M_WRITER_A-E_DO ****
	/* Deletion of the Context/User configuration  */
	DELETE FROM T_LINK_CONTEXT__USER WHERE CONTEXT__USER_CONTEXT_idr = (SELECT CONTEXT_id FROM T_EDIP_CONTEXT WHERE ContextName = 'A400M_Writer_A-E_DO');
	
	/* Add Role to Admin and support */
	INSERT INTO T_LINK_CONTEXT__USER(CONTEXT__USER_CONTEXT_idr, CONTEXT__USER_USER_idr)
		SELECT DISTINCT
			CONTEXT_id,
			USER_id
		FROM
			T_USER,
			T_EDIP_CONTEXT
		WHERE
			ContextName = 'A400M_Writer_A-E_DO' AND
			USER_id 
			IN (
				SELECT
					USER_id
				FROM
					T_USER
					INNER JOIN T_LINK_CONTEXT__USER ON CONTEXT__USER_USER_idr = USER_id
					INNER JOIN T_EDIP_CONTEXT ON CONTEXT__USER_CONTEXT_idr = CONTEXT_id
				WHERE
					ContextName IN ('Admin','Admin_User','A400M_Support','A400M_Admin_data')
			)
					