-- **** UPDATE LOAD IN CIRCE Feature ****
BEGIN
	--PDDS
	
	update T_EDIP_FEATURE SET WhereClause='SELECT * FROM T_PDDS INNER JOIN T_DOMAIN ON DomainName = PDDSDomain INNER JOIN T_LINK_CONTEXT__DOMAIN ON CONTEXT__DOMAIN_DOMAIN_idr = DOMAIN_id INNER JOIN T_LINK_CONTEXT__USER ON CONTEXT__USER_CONTEXT_idr = CONTEXT__DOMAIN_CONTEXT_idr WHERE id_pdds = #data_id# AND pdds_Status = ''CHECKED'' AND PDDSLoadStatus = ''KO'' AND ContextDomainWriteMode = 1 AND CONTEXT__USER_USER_idr = #USER_id#'
	WHERE FeatureLabel = 'Load in CIRCE'
	AND FEATURE_FEATURE_GROUP_IDR = (select FEATURE_GROUP_ID from T_EDIP_FEATURE_GROUP where FeatureGroupLabel = 'PDDS')

END

BEGIN
	--WDDS
	
	update T_EDIP_FEATURE SET WhereClause='SELECT * FROM T_WDDS INNER JOIN T_DOMAIN ON DomainName = WDDSDomain INNER JOIN T_LINK_CONTEXT__DOMAIN ON CONTEXT__DOMAIN_DOMAIN_idr = DOMAIN_id INNER JOIN T_LINK_CONTEXT__USER ON CONTEXT__USER_CONTEXT_idr = CONTEXT__DOMAIN_CONTEXT_idr WHERE WDDS_id = #data_id# AND WDDSStatus = ''HELD'' AND WDDSLoadStatus = ''KO'' AND ContextDomainWriteMode = 1 AND CONTEXT__USER_USER_idr = #USER_id#'
	WHERE FeatureLabel = 'Load in CIRCE'
	AND FEATURE_FEATURE_GROUP_IDR = (select FEATURE_GROUP_ID from T_EDIP_FEATURE_GROUP where FeatureGroupLabel = 'WDDS')
	
END