if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[sp_migrationA400M]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[sp_migrationA400M]
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO



CREATE PROCEDURE  [dbo].[sp_migrationA400M] AS
DECLARE   	@id_ds AS INT, 
		@idr_fin AS INT, 
		@idr_mp AS INT, 
		@ATA AS VARCHAR(255), 
		@DSRefRecup AS VARCHAR(255), 
		@DSRef AS VARCHAR(255),
		@EDDReference AS VARCHAR (255), 
		@RefDs AS VARCHAR (255), 
		@MP AS VARCHAR (255), 
		@MOD AS VARCHAR (255), 
		@FIN AS VARCHAR(255),
		@Pre AS INT,
		@Post AS INT
		
DECLARE   	@DSOrigine AS VARCHAR(255),
		@DSPost AS VARCHAR(255),
		@TypeOfProtection AS VARCHAR (255),
		@Rating AS VARCHAR (255),
		@PowerCenterType AS VARCHAR (255),
		@Panel AS VARCHAR (255),
		@Busbar AS VARCHAR (255),
		@SubBusBar AS VARCHAR (255),
		@Side AS VARCHAR (255),
		@EDDOption AS VARCHAR (255),
		@FINDS_Modifiable AS VARCHAR (255),
		@ICDFD AS VARCHAR (255),
		@AllocatedPhase AS VARCHAR (255),
		@TypePhase AS VARCHAR (255),
		@NominalPower AS VARCHAR (255),
		@NPP1 AS VARCHAR (255),
		@NPP2 AS VARCHAR (255),
		@NPP3 AS VARCHAR (255),
		@PowerFactor AS VARCHAR (255),
		@InrushCurrent AS VARCHAR (255),
		@Duration AS VARCHAR (255),
		@FINDS_Mission AS VARCHAR (255),
		@FINDS_Route AS VARCHAR (255),
		@FINDS_gauge AS VARCHAR (255),
		@FamilyLoad AS VARCHAR (255),
		@OperationalBehaviour AS VARCHAR (255),
		@Sheddable AS VARCHAR (255),
		@TypeACDC AS VARCHAR (255),
		@FINDS_LightCateg AS VARCHAR (255),
		@FINDS_gonogo AS VARCHAR (255),
		@SecuredOpen AS VARCHAR (255),
		@FullProvisionStatus AS VARCHAR (255),
		@Group_ AS VARCHAR (255),
		@SysGPriority AS VARCHAR (255),
		@SysFPriority AS VARCHAR (255),
		@Priority AS VARCHAR (255),
		@FlightPriority AS VARCHAR (255),
		@FINDS_PinAllocDC AS VARCHAR (255),
		@FINDS_PinAllocACPhA AS VARCHAR (255),
		@FINDS_PinAllocACPhB AS VARCHAR (255),
		@FINDS_PinAllocACPhC AS VARCHAR (255),
		@FINDS_PinAllocPowerOutput AS VARCHAR (255),
		@SSPCTypeCard AS VARCHAR (255),
		@FINDS_SSPCFamily AS VARCHAR (255),
		@SSPCAllocatedCardFin AS VARCHAR (255),
		@SSPCChannels AS VARCHAR (255),
		@GFIOption AS VARCHAR (255),
		@FINDS_SSPCAFDOption AS VARCHAR (255),
		@FINDS_SSPCDefaultValue AS VARCHAR (255),
		@DiscreteOutput AS VARCHAR (255),
		@FINDS_SSPCPARAMETER AS VARCHAR (255),
		@FINDS_SSPCVLNAME AS VARCHAR (255),
		@FINDS_SSPCUDPPORT AS VARCHAR (255),
		@FINDS_SSPCVLIdentifier AS VARCHAR (255),
		@FINDS_SSPCSignalAdress AS VARCHAR (255),
		@FINDS_SSPCSignalPos AS VARCHAR (255),
		@FINDS_SSPCStatCon AS VARCHAR (255),
		@FINDS_SSPCStatPin AS VARCHAR (255),
		@FINDS_SSPCCommandType AS VARCHAR (255),
		@FINDS_SSPCCOMMANDPARAMETER AS VARCHAR (255),
		@FINDS_SSPCVLCommandName AS VARCHAR (255),
		--@FINDS_SSPCCOMMANDUDPPORT AS VARCHAR (255),
		--@FINDS_SSPCVLCOMMANDIDENTIFIER AS VARCHAR (255),
		--@FINDS_SSPCCOMMANDSIGNALADRESS AS VARCHAR (255),
		--@FINDS_SSPCCOMMANDSIGNALPOS AS VARCHAR (255),
		@FINDS_SSPCCTLCON AS VARCHAR (255),
		@FINDS_SSPCCTLPIN AS VARCHAR (255),
		@FINDS_RCCBDefaultState AS VARCHAR (255),
		@FINDS_RCCBCommandMode AS VARCHAR (255),
		@FINDS_RCCBTripDelay AS VARCHAR (255),
		@FINDS_RCCBAfdOption AS VARCHAR (255),
		@FINDS_RCCBGFIEnable AS VARCHAR (255),
		@FINDS_RCCBENMFGroup AS VARCHAR (255),
		@FINDS_LRUCode AS VARCHAR (255),
		@ELA_Enveloppe VARCHAR (255),
		@PCDStatCon AS VARCHAR (255),
		@PCDStatPin AS VARCHAR (255),
		@PCDCont1Con AS VARCHAR (255),
		@PCDCont1Pin AS VARCHAR (255),
		@FINDS_TramePosition AS VARCHAR (255),
		@FINDS_CBLOCATION AS VARCHAR (255),
		@FINDS_CBAFDOption AS VARCHAR (255),
		@StartMax AS VARCHAR (255),
		@StartOp AS VARCHAR (255),
		@TakeOffMax AS VARCHAR (255),
		@TakeOffOp AS VARCHAR (255),
		@ClimbMax AS VARCHAR (255),
		@ClimbOp AS VARCHAR (255),
		@CruiseMax AS VARCHAR (255),
		@CruiseOp AS VARCHAR (255),
		@LandingMax AS VARCHAR (255),
		@LandingOp AS VARCHAR (255),
		@TaxiMax AS VARCHAR (255),
		@TaxiOp AS VARCHAR (255),
		@EmerConfMax AS VARCHAR (255),
		@EmerConfOp AS VARCHAR (255),
		@EmerConfOutMax AS VARCHAR (255),
		@EmerConfOutOp AS VARCHAR (255),
		@FINDS_TLMESHighMax AS VARCHAR (255),
		@FINDS_TLMESHighOp AS VARCHAR (255),
		@FINDS_TLMESLowMax AS VARCHAR (255),
		@FINDS_TLMESLowOp AS VARCHAR (255),
		@BatConfMax AS VARCHAR (255),
		@BatConfOp AS VARCHAR (255),
		--@FINDS_ServMax AS VARCHAR (255),
		--@FINDS_ServOp AS VARCHAR (255),
		@FINDS_GroundMax AS VARCHAR (255),
		@FINDS_GroundOp AS VARCHAR (255),
		@FINDS_PullUpMax AS VARCHAR (255),
		@FINDS_PullUpOp AS VARCHAR (255),
		@FINDS_PullDownMax AS VARCHAR (255),
		@FINDS_PullDownOp AS VARCHAR (255),
		@FINDS_DoorsOpMax AS VARCHAR (255),
		@FINDS_DoorsOpOp AS VARCHAR (255),
		@FINDS_KneelingMax AS VARCHAR (255),
		@FINDS_KneelingOp AS VARCHAR (255),
		@FINDS_LoadingMax AS VARCHAR (255),
		@FINDS_LoadingOp AS VARCHAR (255),
		@FINDS_LowLevelMax AS VARCHAR (255),
		@FINDS_LowLevelOp AS VARCHAR (255),
		@FINDS_TMLLFMax AS VARCHAR (255),
		@FINDS_TMLLFOp AS VARCHAR (255),
		@FINDS_AARMax AS VARCHAR (255),
		@FINDS_AAROp AS VARCHAR (255),
		@FINDS_HDUMax AS VARCHAR (255),
		@FINDS_HDUOp AS VARCHAR (255),
		@FINDS_PODMax AS VARCHAR (255),
		@FINDS_PODOp AS VARCHAR (255),
		@FINDS_AerialMax AS VARCHAR (255),
		@FINDS_AerialOp AS VARCHAR (255),
		@FINDS_MedevacMax AS VARCHAR (255),
		@FINDS_MedevacOp AS VARCHAR (255),
		@FINDS_CombatMax AS VARCHAR (255),
		@FINDS_CombatOp AS VARCHAR (255),
		@FINDS_DiversionMax AS VARCHAR (255),
		@FINDS_DiversionOp AS VARCHAR (255),
		@FINDS_SteepMax AS VARCHAR (255),
		@FINDS_SteepOp AS VARCHAR (255),
		@FINDS_TacticalMax AS VARCHAR (255),
		@FINDS_TacticalOp AS VARCHAR (255),
		@Stationary_max AS VARCHAR (255),
		@Stationary_Operationnal AS VARCHAR(255),
		@Autonomous_approach_Max AS VARCHAR(255),
		@Autonomous_approach_Operational AS VARCHAR(255)

DECLARE CURSOR_migrationA400M CURSOR FOR
SELECT 
		ISNULL(TMP_MIGRATION_A400M.[DS_Origine],0),
		TMP_MIGRATION_A400M.[DS_Post],
		TMP_MIGRATION_A400M.[MOD],
		TMP_MIGRATION_A400M.[MP],
		TMP_MIGRATION_A400M.[FIN],		
		TMP_MIGRATION_A400M.[ATA (sub ATA)],
		TMP_MIGRATION_A400M.[Device Type],
		TMP_MIGRATION_A400M.[Rating (A)],
		TMP_MIGRATION_A400M.[Power Center Type],
		TMP_MIGRATION_A400M.[Power Center],
		TMP_MIGRATION_A400M.[Busbar],
		TMP_MIGRATION_A400M.[Sub Busbar],
		TMP_MIGRATION_A400M.[Side],
		TMP_MIGRATION_A400M.[Option],
		TMP_MIGRATION_A400M.[Modifiable],
		TMP_MIGRATION_A400M.[ICD Functional Designation],
		TMP_MIGRATION_A400M.[Allocated Phase],
		TMP_MIGRATION_A400M.[Phase Type],
		TMP_MIGRATION_A400M.[Nominal Power (W or VA)],
		TMP_MIGRATION_A400M.[Nominal Power PhA (VA)],
		TMP_MIGRATION_A400M.[Nominal Power PhB (VA)],
		TMP_MIGRATION_A400M.[Nominal Power PhC (VA)],
		TMP_MIGRATION_A400M.[Power Factor],
		TMP_MIGRATION_A400M.[Inrush Current (A)],
		TMP_MIGRATION_A400M.[Inrush Duration (ms)],
		TMP_MIGRATION_A400M.[Mission],
		TMP_MIGRATION_A400M.[Route],
		TMP_MIGRATION_A400M.[Gauge & Type cable],
		TMP_MIGRATION_A400M.[Family],
		TMP_MIGRATION_A400M.[Operating Mode],
		TMP_MIGRATION_A400M.[Sheddable],
		TMP_MIGRATION_A400M.[AC/DC Type],
		TMP_MIGRATION_A400M.[Lightning category],
		TMP_MIGRATION_A400M.[GO/NOGO],
		TMP_MIGRATION_A400M.[Secured Open],
		TMP_MIGRATION_A400M.[Provision Status],
		TMP_MIGRATION_A400M.[ELMF Group],
		TMP_MIGRATION_A400M.[ELMF System Ground Priority],
		TMP_MIGRATION_A400M.[ELMF System Flight Priority],
		TMP_MIGRATION_A400M.[ELMF Ground Priority],
		TMP_MIGRATION_A400M.[ELMF Flight Priority],
		TMP_MIGRATION_A400M.[PIN Allocation – DC Power Output],
		TMP_MIGRATION_A400M.[PIN Allocation – AC Power Output PhA],
		TMP_MIGRATION_A400M.[PIN Allocation – AC Power Output PhB],
		TMP_MIGRATION_A400M.[PIN Allocation – AC Power Output PhC],
		TMP_MIGRATION_A400M.[Connector Reference – Power Output],
		TMP_MIGRATION_A400M.[Type Card],
		TMP_MIGRATION_A400M.[SSPC Family],
		TMP_MIGRATION_A400M.[Allocated Card FIN],
		TMP_MIGRATION_A400M.[Channel(s)],
		TMP_MIGRATION_A400M.[SSPC GFI Option],
		TMP_MIGRATION_A400M.[SSPC AFD Option],
		TMP_MIGRATION_A400M.[Default Value],
		TMP_MIGRATION_A400M.[SSPC status Discret],
		TMP_MIGRATION_A400M.[Parameter status Name],
		TMP_MIGRATION_A400M.[Status VL name],
		TMP_MIGRATION_A400M.[AFDX: Open/Closed Status],
		TMP_MIGRATION_A400M.[AFDX: 2Tripped Status],
		TMP_MIGRATION_A400M.[AFDX: Validity Status],
		TMP_MIGRATION_A400M.[AFDX: Input Validity Status],
		TMP_MIGRATION_A400M.[SSPC Status Connector],
		TMP_MIGRATION_A400M.[SSPC Status Pin Allocation],
		TMP_MIGRATION_A400M.[Command type],
		TMP_MIGRATION_A400M.[Command parameter Name],
		TMP_MIGRATION_A400M.[Command VL name],
		--TMP_MIGRATION_A400M.[Command UDP Port],
		--TMP_MIGRATION_A400M.[Command VL Identifier],
		--TMP_MIGRATION_A400M.[Command Signal address],
		--TMP_MIGRATION_A400M.[Command Signal position],
		TMP_MIGRATION_A400M.[SSPC CTL Connector],
		TMP_MIGRATION_A400M.[SSPC CTL Pin Allocation],
		TMP_MIGRATION_A400M.[Default State],
		TMP_MIGRATION_A400M.[Command Mode],
		TMP_MIGRATION_A400M.[Trip Delay],
		TMP_MIGRATION_A400M.[RCCB AFD Option],
		TMP_MIGRATION_A400M.[RCCB GFI Option],
		TMP_MIGRATION_A400M.[ENMF Group],
		TMP_MIGRATION_A400M.[LRU Code],
		TMP_MIGRATION_A400M.[RCCB Status Connector],
		TMP_MIGRATION_A400M.[RCCB Status Pin Allocation],
		TMP_MIGRATION_A400M.[RCCB CTL Connector],
		TMP_MIGRATION_A400M.[RCCB CTL Pin Allocation],
		TMP_MIGRATION_A400M.[Trame position],
		TMP_MIGRATION_A400M.[Location],
		TMP_MIGRATION_A400M.[EEPDC C/B AFD Option],
		TMP_MIGRATION_A400M.[ELA Enveloppe ?],
		--TMP_MIGRATION_A400M.[Servicing Max (%)],
		--TMP_MIGRATION_A400M.[Servicing Operational (%)],
		TMP_MIGRATION_A400M.[Ground Max (%)],
		TMP_MIGRATION_A400M.[Ground Operational (%)],
		TMP_MIGRATION_A400M.[Start Max (%)],
		TMP_MIGRATION_A400M.[Start Operational (%)],
		TMP_MIGRATION_A400M.[Take Off Max (%)],
		TMP_MIGRATION_A400M.[Take Off Operational (%)],
		TMP_MIGRATION_A400M.[Climb/Descent Max (%)],
		TMP_MIGRATION_A400M.[Climb/Descent Operational (%)],
		TMP_MIGRATION_A400M.[Cruise Max (%)],
		TMP_MIGRATION_A400M.[Cruise Operational (%)],
		TMP_MIGRATION_A400M.[Landing Max (%)],
		TMP_MIGRATION_A400M.[Landing Operational (%)],
		TMP_MIGRATION_A400M.[Taxi Max (%)],
		TMP_MIGRATION_A400M.[Taxi Operational (%)],
		TMP_MIGRATION_A400M.[TEFO High Speed Max (%) - AC generators inoperative],
		TMP_MIGRATION_A400M.[TEFO High Speed Operational (%) - AC generators inoperative],
		TMP_MIGRATION_A400M.[TEFO Low Speed Max (%) - All engine flame out],
		TMP_MIGRATION_A400M.[TEFO Low Speed Operational (%) - All engine flame out],
		TMP_MIGRATION_A400M.[TLMES High speed Max (%)],
		TMP_MIGRATION_A400M.[TLMES High speed Operational (%)],
		TMP_MIGRATION_A400M.[TLMES Low speed Max (%)],
		TMP_MIGRATION_A400M.[TLMES Low speed Operational (%)],
		--TMP_MIGRATION_A400M.[Refuelling on BAT Max (%)],
		--TMP_MIGRATION_A400M.[Refuelling on BAT Operational (%)],
		TMP_MIGRATION_A400M.[Pull up Max (%)],
		TMP_MIGRATION_A400M.[Pull up Operational (%)],
		TMP_MIGRATION_A400M.[Pull down Max (%)],
		TMP_MIGRATION_A400M.[Pull down Operational (%)],
		TMP_MIGRATION_A400M.[Doors Opening Max (%)],
		TMP_MIGRATION_A400M.[Doors Opening Operational (%)],
		TMP_MIGRATION_A400M.[Kneeling Max (%)],
		TMP_MIGRATION_A400M.[Kneeling Operational (%)],
		TMP_MIGRATION_A400M.[Loading Max (%)],
		TMP_MIGRATION_A400M.[Loading Operational (%)],
		TMP_MIGRATION_A400M.[Low Level Flight Max (%)],
		TMP_MIGRATION_A400M.[Low Level Flight Operational (%)],
		TMP_MIGRATION_A400M.[TMLLF Max (%)],
		TMP_MIGRATION_A400M.[TMLLF Operational (%)],
		TMP_MIGRATION_A400M.[AAR receipt Max (%)],
		TMP_MIGRATION_A400M.[AAR receipt Operational (%)],
		TMP_MIGRATION_A400M.[AAR Dispensing with HDU Max (%)],
		TMP_MIGRATION_A400M.[AAR Dispensing with HDU Operational (%)],
		TMP_MIGRATION_A400M.[AAR Dispensing with Pod Max (%)],
		TMP_MIGRATION_A400M.[AAR Dispensing with Pod Operational (%)],
		TMP_MIGRATION_A400M.[Aerial delivery Max (%)],
		TMP_MIGRATION_A400M.[Aerial delivery Operational (%)],
		TMP_MIGRATION_A400M.[Medevac Max (%)],
		TMP_MIGRATION_A400M.[Medevac Operational (%)],
		TMP_MIGRATION_A400M.[Combat offload Max (%)],
		TMP_MIGRATION_A400M.[Combat offload Operational (%)],
		TMP_MIGRATION_A400M.[Diversion Max (%)],
		TMP_MIGRATION_A400M.[Diversion Operational (%)],
		TMP_MIGRATION_A400M.[Steep Descent Max (%)],
		TMP_MIGRATION_A400M.[Steep Descent Operational (%)],
		TMP_MIGRATION_A400M.[Step Tactical approach Max (%)],
		TMP_MIGRATION_A400M.[Step Tactical approach Operational (%)],
		TMP_MIGRATION_A400M.[A/C Stationary Max (%)],
		TMP_MIGRATION_A400M.[A/C Stationary Operational (%)],
		TMP_MIGRATION_A400M.[Autonomous approach Max (%)],
		TMP_MIGRATION_A400M.[Autonomous approach Operational (%)]
FROM TMP_MIGRATION_A400M
ORDER BY [FIN], [DS_Post]

OPEN CURSOR_migrationA400M
FETCH NEXT FROM CURSOR_migrationA400M INTO

		@DSOrigine,
		@DSPost,
		@MOD,
		@MP,
		@FIN,
		@ATA,
		@TypeOfProtection,
		@Rating,
		@PowerCenterType,
		@Panel,
		@Busbar,
		@SubBusBar,
		@Side,
		@EDDOption,
		@FINDS_Modifiable,
		@ICDFD,
		@AllocatedPhase,
		@TypePhase,
		@NominalPower,
		@NPP1,
		@NPP2,
		@NPP3,
		@PowerFactor,
		@InrushCurrent,
		@Duration,
		@FINDS_Mission,
		@FINDS_Route,
		@FINDS_gauge,
		@FamilyLoad,
		@OperationalBehaviour,
		@Sheddable,
		@TypeACDC,
		@FINDS_LightCateg,
		@FINDS_gonogo,
		@SecuredOpen,
		@FullProvisionStatus,
		@Group_,
		@SysGPriority,
		@SysFPriority,
		@Priority,
		@FlightPriority,
		@FINDS_PinAllocDC,
		@FINDS_PinAllocACPhA,
		@FINDS_PinAllocACPhB,
		@FINDS_PinAllocACPhC,
		@FINDS_PinAllocPowerOutput,
		@SSPCTypeCard,
		@FINDS_SSPCFamily,
		@SSPCAllocatedCardFin,
		@SSPCChannels,
		@GFIOption,
		@FINDS_SSPCAFDOption,
		@FINDS_SSPCDefaultValue,
		@DiscreteOutput,
		@FINDS_SSPCPARAMETER,
		@FINDS_SSPCVLNAME,
		@FINDS_SSPCUDPPORT,
		@FINDS_SSPCVLIdentifier,
		@FINDS_SSPCSignalAdress,
		@FINDS_SSPCSignalPos,
		@FINDS_SSPCStatCon,
		@FINDS_SSPCStatPin,
		@FINDS_SSPCCommandType,
		@FINDS_SSPCCOMMANDPARAMETER,
		@FINDS_SSPCVLCommandName,
		--@FINDS_SSPCCOMMANDUDPPORT,
		--@FINDS_SSPCVLCOMMANDIDENTIFIER,
		--@FINDS_SSPCCOMMANDSIGNALADRESS,
		--@FINDS_SSPCCOMMANDSIGNALPOS,
		@FINDS_SSPCCTLCON,
		@FINDS_SSPCCTLPIN,
		@FINDS_RCCBDefaultState,
		@FINDS_RCCBCommandMode,
		@FINDS_RCCBTripDelay,
		@FINDS_RCCBAfdOption,
		@FINDS_RCCBGFIEnable,
		@FINDS_RCCBENMFGroup,
		@FINDS_LRUCode,
		@PCDStatCon,
		@PCDStatPin,
		@PCDCont1Con,
		@PCDCont1Pin,
		@FINDS_TramePosition,
		@FINDS_CBLOCATION,
		@FINDS_CBAFDOption,
		@ELA_Enveloppe,
		--@FINDS_ServMax,
		--@FINDS_ServOp,
		@FINDS_GroundMax,
		@FINDS_GroundOp,
		@StartMax,
		@StartOp,
		@TakeOffMax,
		@TakeOffOp,
		@ClimbMax,
		@ClimbOp,
		@CruiseMax,
		@CruiseOp,
		@LandingMax,
		@LandingOp,
		@TaxiMax,
		@TaxiOp,
		@EmerConfMax,
		@EmerConfOp,
		@EmerConfOutMax,
		@EmerConfOutOp,
		@FINDS_TLMESHighMax,
		@FINDS_TLMESHighOp,
		@FINDS_TLMESLowMax,
		@FINDS_TLMESLowOp,
		--@BatConfMax,
		--@BatConfOp,
		@FINDS_PullUpMax,
		@FINDS_PullUpOp,
		@FINDS_PullDownMax,
		@FINDS_PullDownOp,
		@FINDS_DoorsOpMax,
		@FINDS_DoorsOpOp,
		@FINDS_KneelingMax,
		@FINDS_KneelingOp,
		@FINDS_LoadingMax,
		@FINDS_LoadingOp,
		@FINDS_LowLevelMax,
		@FINDS_LowLevelOp,
		@FINDS_TMLLFMax,
		@FINDS_TMLLFOp,
		@FINDS_AARMax,
		@FINDS_AAROp,
		@FINDS_HDUMax,
		@FINDS_HDUOp,
		@FINDS_PODMax,
		@FINDS_PODOp,
		@FINDS_AerialMax,
		@FINDS_AerialOp,
		@FINDS_MedevacMax,
		@FINDS_MedevacOp,
		@FINDS_CombatMax,
		@FINDS_CombatOp,
		@FINDS_DiversionMax,
		@FINDS_DiversionOp,
		@FINDS_SteepMax,
		@FINDS_SteepOp,
		@FINDS_TacticalMax,
		@FINDS_TacticalOp,
		@Stationary_max,
		@Stationary_Operationnal,
		@Autonomous_approach_Max,
		@Autonomous_approach_Operational
		
WHILE @@FETCH_STATUS = 0
BEGIN  

	SET @idr_fin = ''
	SET @idr_mp = ''
		
	-- GET FIN id
	SELECT @idr_fin = id_fin 
	FROM R_FIN_CI
	WHERE R_FIN_CI.FIN = @FIN
	
	print @idr_fin
	
	-- Get MP id
	SELECT @idr_mp = id_MP 
	FROM T_MP
	WHERE T_MP.MPReference = @MP
	
	SET @id_ds = ''
	
	SET @DSRefRecup = ''
	select @DSRefRecup = max(RefDs) + 1 from R_FIN_DS where idr_fin = @idr_fin and ds_type = 4
	
	print 'Recup'+@DSRefRecup
	
	IF @DSRefRecup ='' or @DSRefRecup is null
	BEGIN
		SET @DSRef = '0001'
	END 
	ELSE
	BEGIN
		Set @DSRef = '000' + @DSRefRecup
	END
	SELECT
		@EDDReference = ATACode + Circuit_Letter + TMP_MIGRATION_A400M.[AC/DC Type] +
		REPLICATE('0', 6 - LEN(CONVERT(VARCHAR(8000), ISNULL((SELECT MAX(CONVERT(INTEGER, SUBSTRING(EDDReference, 9, 6)) + 1) FROM R_FIN_DS WHERE LEFT(EDDReference, 4) = ATACode), 0)))) + CONVERT(VARCHAR(8000),ISNULL((SELECT MAX(CONVERT(INTEGER, SUBSTRING(EDDReference, 9, 6)) + 1) FROM R_FIN_DS WHERE LEFT(EDDReference, 4) = ATACode), 0))
		+ 'V000'
	FROM
		TMP_MIGRATION_A400M
	        JOIN R_FIN_CI ON R_FIN_CI.FIN = TMP_MIGRATION_A400M.[FIN]
	        JOIN R_ATA ON R_ATA.id_ata = R_FIN_CI.idr_ata
	WHERE R_FIN_CI.FIN = @FIN	
	INSERT INTO R_FIN_DS
	(
		EDDMOD,
		RefDS,
		idr_fin,
		EDDReference,
		VALM0,
		VALM1,
		VALM2,
		MG,
		ds_type,
		TypeOfProtection,
		Rating,
		PowerCenterType,
		Panel,
		Busbar,
		SubBusBar,
		Side,
		EDDOption,
		FINDS_Modifiable,
		ICDFD,
		AllocatedPhase,
		TypePhase,
		NominalPower,
		NPP1,
		NPP2,
		NPP3,
		PowerFactor,
		InrushCurrent,
		Duration,
		FINDS_Mission,
		FINDS_Route,
		FINDS_gauge,
		FamilyLoad,
		OperationalBehaviour,
		Sheddable,
		TypeACDC,
		FINDS_LightCateg,
		FINDS_gonogo,
		SecuredOpen,
		FullProvisionStatus,
		Group_,
		SysGPriority,
		SysFPriority,
		Priority,
		FlightPriority,
		FINDS_PinAllocDC,
		FINDS_PinAllocACPhA,
		FINDS_PinAllocACPhB,
		FINDS_PinAllocACPhC,
		FINDS_PinAllocPowerOutput,
		SSPCTypeCard,
		FINDS_SSPCFamily,
		SSPCAllocatedCardFin,
		SSPCChannels,
		SSPC_GFI_Option,
		FINDS_SSPCAFDOption,
		FINDS_SSPCDefaultValue,
		DiscreteOutput,
		FINDS_SSPCPARAMETER,
		FINDS_SSPCVLNAME,
		FINDS_AFDXOPENCLOSEDSTATUS,
		FINDS_AFDXTrippedStatus,
		FINDS_AFDXValidityStatus,
		FINDS_AFDXInputValidityStatus,
		FINDS_SSPCStatCon,
		FINDS_SSPCStatPin,
		FINDS_SSPCCommandType,
		FINDS_SSPCCOMMANDPARAMETER,
		FINDS_SSPCVLCommandName,
		--FINDS_SSPCCOMMANDUDPPORT,
		--FINDS_SSPCVLCOMMANDIDENTIFIER,
		--FINDS_SSPCCOMMANDSIGNALADRESS,
		--FINDS_SSPCCOMMANDSIGNALPOS,
		FINDS_SSPCCTLCON,
		FINDS_SSPCCTLPIN,
		FINDS_RCCBDefaultState,
		FINDS_RCCBCommandMode,
		FINDS_RCCBTripDelay,
		FINDS_RCCBAfdOption,
		FINDS_RCCBGFIOption,
		FINDS_RCCBENMFGroup,
		FINDS_LRUCode,
		PCDStatCon,
		PCDStatPin,
		PCDCont1Con,
		PCDCont1Pin,
		FINDS_TramePosition,
-- Change Starts Here 09/10
-- Replace FINDS_CBLOCATION from C/B Group to EEPDC Group
--		FINDS_CBLOCATION,
		LOCATION,
-- Change Stops here
		FINDS_CBAFDOption,
		StartMax,
		StartOp,
		TakeOffMax,
		TakeOffOp,
		ClimbMax,
		ClimbOp,
		CruiseMax,
		CruiseOp,
		LandingMax,
		LandingOp,
		TaxiMax,
		TaxiOp,
		EmerConfMax,
		EmerConfOp,
		EmerConfOutMax,
		EmerConfOutOp,
		FINDS_TLMESHighMax,
		FINDS_TLMESHighOp,
		FINDS_TLMESLowMax,
		FINDS_TLMESLowOp,
		ELA_Enveloppe,
		--BatConfMax,
		--BatConfOp,
		--FINDS_ServMax,
		--FINDS_ServOp,
		FINDS_GroundMax,
		FINDS_GroundOp,
		FINDS_PullUpMax,
		FINDS_PullUpOp,
		FINDS_PullDownMax,
		FINDS_PullDownOp,
		FINDS_DoorsOpMax,
		FINDS_DoorsOpOp,
		FINDS_KneelingMax,
		FINDS_KneelingOp,
		FINDS_LoadingMax,
		FINDS_LoadingOp,
		FINDS_LowLevelMax,
		FINDS_LowLevelOp,
		FINDS_TMLLFMax,
		FINDS_TMLLFOp,
		FINDS_AARMax,
		FINDS_AAROp,
		FINDS_HDUMax,
		FINDS_HDUOp,
		FINDS_PODMax,
		FINDS_PODOp,
		FINDS_AerialMax,
		FINDS_AerialOp,
		FINDS_MedevacMax,
		FINDS_MedevacOp,
		FINDS_CombatMax,
		FINDS_CombatOp,
		FINDS_DiversionMax,
		FINDS_DiversionOp,
		FINDS_SteepMax,
		FINDS_SteepOp,
		FINDS_TacticalMax,
		FINDS_TacticalOp,
		Stationary_max,
		Stationary_Operationnal,
		FINDS_approach_Max,
		FINDS_approach_Operational
	)
	VALUES
	(
		@MOD,
		@DSRef,
		@idr_fin,
		@EDDReference,
		'Not validated',
		'Not validated',
		'Not validated',
		0,
		4,
		@TypeOfProtection,
		REPLACE(@Rating,',','.'),
		@PowerCenterType,
		@Panel,
		@Busbar,
		@SubBusBar,
		@Side,
		@EDDOption,
		@FINDS_Modifiable,
		@ICDFD,
		@AllocatedPhase,
		@TypePhase,
		REPLACE(@NominalPower,',','.'),
		REPLACE(@NPP1,',','.'),
		REPLACE(@NPP2,',','.'),
		REPLACE(@NPP3,',','.'),
		REPLACE(@PowerFactor,',','.'),
		REPLACE(@InrushCurrent,',','.'),
		@Duration,
		@FINDS_Mission,
		@FINDS_Route,
		@FINDS_gauge,
		@FamilyLoad,
		@OperationalBehaviour,
		@Sheddable,
		@TypeACDC,
		@FINDS_LightCateg,
		@FINDS_gonogo,
		@SecuredOpen,
		@FullProvisionStatus,
		@Group_,
		@SysGPriority,
		@SysFPriority,
		@Priority,
		@FlightPriority,
		@FINDS_PinAllocDC,
		@FINDS_PinAllocACPhA,
		@FINDS_PinAllocACPhB,
		@FINDS_PinAllocACPhC,
		@FINDS_PinAllocPowerOutput,
		@SSPCTypeCard,
		@FINDS_SSPCFamily,
		@SSPCAllocatedCardFin,
		@SSPCChannels,
		@GFIOption,
		@FINDS_SSPCAFDOption,
		@FINDS_SSPCDefaultValue,
		@DiscreteOutput,
		@FINDS_SSPCPARAMETER,
		@FINDS_SSPCVLNAME,
		@FINDS_SSPCUDPPORT,
		@FINDS_SSPCVLIdentifier,
		@FINDS_SSPCSignalAdress,
		@FINDS_SSPCSignalPos,
		@FINDS_SSPCStatCon,
		@FINDS_SSPCStatPin,
		@FINDS_SSPCCommandType,
		@FINDS_SSPCCOMMANDPARAMETER,
		@FINDS_SSPCVLCommandName,
		--@FINDS_SSPCCOMMANDUDPPORT,
		--@FINDS_SSPCVLCOMMANDIDENTIFIER,
		--@FINDS_SSPCCOMMANDSIGNALADRESS,
		--@FINDS_SSPCCOMMANDSIGNALPOS,
		@FINDS_SSPCCTLCON,
		@FINDS_SSPCCTLPIN,
		@FINDS_RCCBDefaultState,
		@FINDS_RCCBCommandMode,
		@FINDS_RCCBTripDelay,
		@FINDS_RCCBAfdOption,
		@FINDS_RCCBGFIEnable,
		@FINDS_RCCBENMFGroup,
		@FINDS_LRUCode,
		@PCDStatCon,
		@PCDStatPin,
		@PCDCont1Con,
		@PCDCont1Pin,
		@FINDS_TramePosition,
		@FINDS_CBLOCATION,
		@FINDS_CBAFDOption,
		@StartMax,
		@StartOp,
		@TakeOffMax,
		@TakeOffOp,
		@ClimbMax,
		@ClimbOp,
		@CruiseMax,
		@CruiseOp,
		@LandingMax,
		@LandingOp,
		@TaxiMax,
		@TaxiOp,
		@EmerConfMax,
		@EmerConfOp,
		@EmerConfOutMax,
		@EmerConfOutOp,
		@FINDS_TLMESHighMax,
		@FINDS_TLMESHighOp,
		@FINDS_TLMESLowMax,
		@FINDS_TLMESLowOp,
		@ELA_Enveloppe,
		--@BatConfMax,
		--@BatConfOp,
		--@FINDS_ServMax,
		--@FINDS_ServOp,
		@FINDS_GroundMax,
		@FINDS_GroundOp,
		@FINDS_PullUpMax,
		@FINDS_PullUpOp,
		@FINDS_PullDownMax,
		@FINDS_PullDownOp,
		@FINDS_DoorsOpMax,
		@FINDS_DoorsOpOp,
		@FINDS_KneelingMax,
		@FINDS_KneelingOp,
		@FINDS_LoadingMax,
		@FINDS_LoadingOp,
		@FINDS_LowLevelMax,
		@FINDS_LowLevelOp,
		@FINDS_TMLLFMax,
		@FINDS_TMLLFOp,
		@FINDS_AARMax,
		@FINDS_AAROp,
		@FINDS_HDUMax,
		@FINDS_HDUOp,
		@FINDS_PODMax,
		@FINDS_PODOp,
		@FINDS_AerialMax,
		@FINDS_AerialOp,
		@FINDS_MedevacMax,
		@FINDS_MedevacOp,
		@FINDS_CombatMax,
		@FINDS_CombatOp,
		@FINDS_DiversionMax,
		@FINDS_DiversionOp,
		@FINDS_SteepMax,
		@FINDS_SteepOp,
		@FINDS_TacticalMax,
		@FINDS_TacticalOp,
		@Stationary_max,
		@Stationary_Operationnal,
		@Autonomous_approach_Max,
		@Autonomous_approach_Operational
	)
	

	--IMPACT
	-- PRE
	IF @MP <> ''
	BEGIN
		IF @DSOrigine = 0 
		BEGIN
			SET @Pre = 0
		END
		ELSE		
		BEGIN
			SELECT @Pre = id_ds FROM R_FIN_DS WHERE RefDS like '%'+@DSOrigine and idr_fin = @idr_fin and ds_type = 4
			
		END 
		-- POST
		SELECT @Post = id_ds FROM R_FIN_DS WHERE RefDS = @DsRef and idr_fin = @idr_fin	
		INSERT INTO T_IMPACTDS (idr_ds_pre,idr_ds_post,idr_mp,idr_si) VALUES (@Pre, @Post, @idr_mp, 0)
	END
	-- END IMPACT	

FETCH NEXT FROM CURSOR_migrationA400M INTO
		@DSOrigine,
		@DSPost,
		@MOD,
		@MP,
		@FIN,
		@ATA,
		@TypeOfProtection,
		@Rating,
		@PowerCenterType,
		@Panel,
		@Busbar,
		@SubBusBar,
		@Side,
		@EDDOption,
		@FINDS_Modifiable,
		@ICDFD,
		@AllocatedPhase,
		@TypePhase,
		@NominalPower,
		@NPP1,
		@NPP2,
		@NPP3,
		@PowerFactor,
		@InrushCurrent,
		@Duration,
		@FINDS_Mission,
		@FINDS_Route,

		@FINDS_gauge,
		@FamilyLoad,
		@OperationalBehaviour,
		@Sheddable,
		@TypeACDC,
		@FINDS_LightCateg,
		@FINDS_gonogo,
		@SecuredOpen,
		@FullProvisionStatus,
		@Group_,
		@SysGPriority,
		@SysFPriority,
		@Priority,
		@FlightPriority,
		@FINDS_PinAllocDC,
		@FINDS_PinAllocACPhA,
		@FINDS_PinAllocACPhB,
		@FINDS_PinAllocACPhC,
		@FINDS_PinAllocPowerOutput,
		@SSPCTypeCard,
		@FINDS_SSPCFamily,
		@SSPCAllocatedCardFin,
		@SSPCChannels,
		@GFIOption,
		@FINDS_SSPCAFDOption,
		@FINDS_SSPCDefaultValue,
		@DiscreteOutput,
		@FINDS_SSPCPARAMETER,
		@FINDS_SSPCVLNAME,
		@FINDS_SSPCUDPPORT,
		@FINDS_SSPCVLIdentifier,
		@FINDS_SSPCSignalAdress,
		@FINDS_SSPCSignalPos,
		@FINDS_SSPCStatCon,
		@FINDS_SSPCStatPin,
		@FINDS_SSPCCommandType,
		@FINDS_SSPCCOMMANDPARAMETER,
		@FINDS_SSPCVLCommandName,
		--@FINDS_SSPCCOMMANDUDPPORT,
		--@FINDS_SSPCVLCOMMANDIDENTIFIER,
		--@FINDS_SSPCCOMMANDSIGNALADRESS,
		--@FINDS_SSPCCOMMANDSIGNALPOS,
		@FINDS_SSPCCTLCON,
		@FINDS_SSPCCTLPIN,
		@FINDS_RCCBDefaultState,
		@FINDS_RCCBCommandMode,
		@FINDS_RCCBTripDelay,
		@FINDS_RCCBAfdOption,
		@FINDS_RCCBGFIEnable,
		@FINDS_RCCBENMFGroup,
		@FINDS_LRUCode,
		@PCDStatCon,
		@PCDStatPin,
		@PCDCont1Con,
		@PCDCont1Pin,
		@FINDS_TramePosition,
		@FINDS_CBLOCATION,
		@FINDS_CBAFDOption,
		@Ela_enveloppe,
		--@FINDS_ServMax,
		--@FINDS_ServOp,
		@FINDS_GroundMax,
		@FINDS_GroundOp,
		@StartMax,
		@StartOp,
		@TakeOffMax,
		@TakeOffOp,
		@ClimbMax,
		@ClimbOp,
		@CruiseMax,
		@CruiseOp,
		@LandingMax,
		@LandingOp,
		@TaxiMax,
		@TaxiOp,
		@EmerConfMax,
		@EmerConfOp,
		@EmerConfOutMax,
		@EmerConfOutOp,
		@FINDS_TLMESHighMax,
		@FINDS_TLMESHighOp,
		@FINDS_TLMESLowMax,
		@FINDS_TLMESLowOp,
		--@BatConfMax,
		--@BatConfOp,
		@FINDS_PullUpMax,
		@FINDS_PullUpOp,
		@FINDS_PullDownMax,
		@FINDS_PullDownOp,
		@FINDS_DoorsOpMax,
		@FINDS_DoorsOpOp,
		@FINDS_KneelingMax,
		@FINDS_KneelingOp,
		@FINDS_LoadingMax,
		@FINDS_LoadingOp,
		@FINDS_LowLevelMax,
		@FINDS_LowLevelOp,
		@FINDS_TMLLFMax,
		@FINDS_TMLLFOp,
		@FINDS_AARMax,
		@FINDS_AAROp,
		@FINDS_HDUMax,
		@FINDS_HDUOp,
		@FINDS_PODMax,
		@FINDS_PODOp,
		@FINDS_AerialMax,
		@FINDS_AerialOp,
		@FINDS_MedevacMax,
		@FINDS_MedevacOp,
		@FINDS_CombatMax,
		@FINDS_CombatOp,
		@FINDS_DiversionMax,
		@FINDS_DiversionOp,
		@FINDS_SteepMax,
		@FINDS_SteepOp,
		@FINDS_TacticalMax,
		@FINDS_TacticalOp,
		@Stationary_max,
		@Stationary_Operationnal,
		@Autonomous_approach_Max,
		@Autonomous_approach_Operational


END
CLOSE CURSOR_migrationA400M
DEALLOCATE CURSOR_migrationA400M
UPDATE R_FIN_DS SET RefDS = '' WHERE ds_type = 4 and MG = 0

SELECT   ATACode AS [ATA] , circuit_letter AS [Circuit Letter], FIN AS [FIN], TypeACDC AS [AC/DC Type],DsPost AS [EDD created], MP AS [MP],  DsPre as [EDD Pre]
FROM   (        
		SELECT     
			distinct ATACode,			
			circuit_letter,
			R_FIN_CI.FIN,
			r_fin_ds.TypeACDC,
			CASE      
			  WHEN IMPACT.EDDReference is null THEN 'BLANK'      			  			  
			  WHEN IMPACT.EDDReference IS NOT NULL THEN IMPACT.EDDReference        
			  ELSE ''
			END AS DSPre,		
			R_FIN_DS.EDDReference AS DsPost,
			MPReference AS MP		
			
		FROM    R_FIN_DS
			JOIN R_FIN_CI on R_FIN_CI.id_fin = R_FIN_Ds.idr_fin
			JOIN TMP_MIGRATION_A400M ON TMP_MIGRATION_A400M.FIN = R_FIN_CI.FIN
			JOIN R_ATA on R_FIN_CI.idr_ata = R_ATA.id_ata
		LEFT JOIN      
		(      
			SELECT       idr_ds_post,       
				     MPReference,       
				     id_mp,       
				     idr_ds_pre,      
				     RefDs,       
				     EDDReference      
			FROM       T_IMPACTDS       
			  	JOIN T_MP ON T_MP.id_mp = T_IMPACTDS.idr_mp       
				LEFT JOIN R_FIN_DS ON R_FIN_DS.id_ds = T_IMPACTDS.idr_ds_pre and r_fin_ds.ds_type=4
	       ) IMPACT 
			ON IMPACT.idr_ds_post = R_FIN_DS.id_ds  --AND       ds_type = 4
  		WHERE r_fin_ds.ds_type=4
			
	) AS TMP
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

