/* Bruno Sanguinede

Bonjour,

On commence la dernière partie de la migration des données Elcodata sur l'A400M. Parmi toutes les joyeusetés, il y a le passage des maturity gates par Mass Loading vu que c'est un rattrapage d'une validation déjà faite. On va faire ça par script sql qui met à jour la MG + les notifications + loggue l'action dans l'historique pour tracer la manip. Le premier passage à MG2 déclanche l'envoi à System View.

Vu que je n'ai trop d'infos sur l'import SV sur la machine A400M, je propose de commencer "petit bras" et ensuite de découper le mass loading en fonction du résultat de l'import (autrement dit, chaque soir, je m'autorise 30 minutes d'import dans SV max).

Voici donc le premier script pour 50 EDDs à passer. J'aimerais le passer en Val PSE A400M (FR0-PSSA4M-V01\DBWVE120 DBWVPSE_A400M) avant, au moins la première fois, pour roder la manip (je l'ai fait chez moi en training déjà).

Ensuite, en PROD PSE A400M (FR0-PSSA4M01\DBWPE120 DBWPPSE_A400M).

*/
declare 
  @userid integer


set @userid = (select user_id from t_user where user_logon='ST17877')

-- Copy Update here
--UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1722AGDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1722AGDC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='1852NSAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2131HLDC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2131HLDC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2142HJAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2142HJAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2153HHDC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2153HHDC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2278CADC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2281CBDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2281CBDC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000004'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2329RCDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEAC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEDC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEDC000004'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2426XOAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2426XOAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2473XZDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2511MSAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2547MTAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2547MTAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000004'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000004'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000005'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000006'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000007'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000008'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000009'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000010'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000011'


-- Copy update hsitory here
--INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1722AGDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1722AGDC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1851NVAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='1852NSAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2122HEAC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2131HLDC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2131HLDC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2142HJAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2142HJAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2153HHDC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2153HHDC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2278CADC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2281CBDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2281CBDC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2328RVAC000004'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2329RCDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEAC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEDC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2424XEDC000004'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2426XOAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2426XOAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2473XZDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2511MSAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2547MTAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2547MTAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2552MYDC000004'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000004'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000005'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000006'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYAC000007'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000008'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000009'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000010'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2553MYDC000011'
