declare 
  @userid integer


set @userid = (select user_id from t_user where user_logon='ST17877')

-- Copy Update here
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000001'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000002'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000003'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000004'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000005'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000006'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000007'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000010'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000011'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000012'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000014'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000015'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000021'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000022'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000063'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000063'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000024'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000025'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000027'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000028'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000029'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000036'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000037'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000038'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000040'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000041'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000042'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000043'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000044'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000045'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000046'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000047'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000050'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000051'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000052'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000053'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000054'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000055'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000057'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000058'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000059'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000060'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000061'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='3322LGDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='3322LGDC000000'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2422XUDC000016'
UPDATE R_fin_ds set valm0='Validated',valm1='Validated',mg='2' WHERE substring(R_FIN_DS.EDDReference,1,14)='2422XUDC000017'


-- Copy update hsitory here
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000001'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000002'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000003'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000004'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000005'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000006'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000007'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000010'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000011'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000012'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000014'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000015'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000021'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000022'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000063'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000063'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000024'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000025'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000027'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000028'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000029'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000036'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000037'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000038'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000040'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000041'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000042'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000043'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000044'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000045'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000046'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000047'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000050'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000051'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000052'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000053'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000054'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000055'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000057'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000058'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZDC000059'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000060'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2472XZAC000061'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='3322LGDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='3322LGDC000000'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2422XUDC000016'
INSERT INTO T_History (logon,history_idr_user,ActionDate,ActionType,ActionData,ObjectReference,ActionDesc,ActionObject,RefId) SELECT 'EPC ADMIN',@userid,GETDATE(),'Upgrading MG Level','From MG 0 to MG 2',EddReference,'','DS',R_FIN_DS.id_ds FROM R_FIN_DS WHERE substring(R_FIN_DS.EDDReference,1,14)='2422XUDC000017'


