UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=1
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=2
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=3
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=4
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=5
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=6
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=7
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=8
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=9
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=10
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=11
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=12
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=13
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=14
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=15
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=16
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=17
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=18
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=19
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=20
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=21
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=22
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=23
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=24
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=25
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=26
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=27
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=28
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=29
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=30
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=31
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=32
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=33
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=34
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=35
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=36
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=37
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=38
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=39
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=40
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=41
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=42
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=43
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=44
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=45
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=46
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=47
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=48
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=49
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=50
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=51
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=52
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=53
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=54
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=55
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=56
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=57
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=58
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=59
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=60
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=61
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=62
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=63
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=64
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=65
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=66
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=67
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=68
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=69
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=70
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=71
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=72
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=73
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=74
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=75
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=76
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=77
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=78
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=79
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=80
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=81
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=82
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=83
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=84
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=85
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=86
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=87
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=88
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=89
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=90
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=91
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=92
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=93
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=94
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=95
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=96
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=97
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=98
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=99
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=100
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=101
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=102
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=103
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5000
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5001
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5002
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5003
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5004
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5005
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5006
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5007
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5008
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5009
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5010
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5011
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5012
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5013
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5014
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5015
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5016
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5017
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5018
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5019
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5020
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5021
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5022
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5023
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5024
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5025
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5026
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5027
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5028
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5029
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5030
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5031
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=5032
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=5080
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=7500
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=7999
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8002
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8004
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8007
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8009
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=8014
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8017
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=8027
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=8029
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8350
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=8999
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD8.0'          WHERE    MSN=9007
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9010
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9011
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9012
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9013
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9014
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9015
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9016
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9017
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9019
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9020
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9021
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9022
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9023
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9025
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9026
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9027
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9028
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9029
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9031
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9033
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9034
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9038
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9040
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9043
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9045
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9047
UPDATE     T_MSN    SET    MSN_SEPDS_PED_Standard='STD6.4.1'          WHERE    MSN=9050
