-----------------------------------------------------------
-- Report Consolidated MSN Definition for MIS V1.0
-----------------------------------------------------------

-- Drop Consolidated MSN Definition for MIS Procedure

IF EXISTS (SELECT name FROM sysobjects WHERE name = 'sp_Consolidated_MSN_Definition_for_MIS' AND type = 'P')
   DROP PROCEDURE sp_Consolidated_MSN_Definition_for_MIS
GO


-- Global MSN definition Report creation in PSE

IF (SELECT REPORT_GROUP_id FROM T_REPORT_GROUP WHERE REPORT_GROUP_LABEL = 'MSN Definition') IS NULL
	INSERT INTO [T_REPORT_GROUP]
	(
		[REPORT_GROUP_LABEL]
	)
	VALUES
	(
		'MSN Definition'
	)

DECLARE
	@AttGroup INT

SELECT @AttGroup = REPORT_GROUP_id FROM T_REPORT_GROUP WHERE REPORT_GROUP_LABEL = 'MSN Definition'

-- Add report
DELETE T_DBActions WHERE label = 'Consolidated MSN Definition for MIS'

INSERT INTO [T_DBActions]
(
	[label],
	[command],
	[comments],
	[template_page],
	[parameters],
	[report_commentary],
	[mandatory_fields],
	[report_group_idr]
)
VALUES
(
	'Consolidated MSN Definition for MIS',
	'SELECT
	*
FROM
	OPENQUERY(R_PSS_A400M, ''
SELECT
	m.MSN [MSN],
	m.ATA [SUBATA-DS Name],
	f.FIN [FIN-CI Name],
	f.Status [FIN-CI Status],
	f.FINCategory [FIN-CI Category],
	f.FUNCTIONALDESIGNATION [FIN-CI Functional Designation],
	m.[FIN-CI Definition Resp. NatCo] [FIN-CI Definition Resp. NatCo],
	m.[FIN-CI Design Focal Point] [FIN-CI Design Focal Point],
	m.[FIN-CI Installation Site] [FIN-CI Installation Site],
	m.[FIN-CI Provisioning Site] [FIN-CI Provisioning Site],
	m.[FIN-CI Installation Design Resp] [FIN-CI Installation Design Resp],
	m.[FIN-CI OBS] [FIN-CI OBS],
	f.WCLCODE [FIN-CI WCL Code],
	f.AC_ICDrootFileName [FIN-CI AC/ICD Root File Name],
	f.AC_ICDfolderName [FIN-CI ICD Folder Name],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.SKETCH ELSE s.SKETCH END [FIN-DS CA],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.BWTPARTNUMBER ELSE s.BWTPARTNUMBER END [FIN-DS Name],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.PURCHASEQTY ELSE s.PURCHASEQTY END [FIN-DS Purchase Quantity],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.STATESTATE ELSE s.STATESTATE END [FIN-DS State],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN '''''''''''''''' + sd.LASTDEVEFFECTIVITY + '''''''''''''''' ELSE '''''''''''''''' + g.RANGE + '''''''''''''''' END [FIN-DS Effectivity],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.AIRRECORDED ELSE s.AIRRECORDED END [FIN-DS AIR Recorded],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN zd.UNIQUEID ELSE z.UNIQUEID END [FIN-DS Installation Zone],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.INSTRPROCEDURE ELSE s.INSTRPROCEDURE END [FIN-DS Installation Section],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN nd.UNIQUEID ELSE n.UNIQUEID END [FIN-DS Installation Panel],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.PROVISIONINGTYPE ELSE s.PROVISIONINGTYPE END [FIN-DS provisioning type],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN RIGHT(cd.UNIQUEID, LEN(cd.UNIQUEID) - 1) ELSE RIGHT(c.UNIQUEID, LEN(c.UNIQUEID) - 1) END [FIN-DS ANSI Code],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN sd.LOADINGTYPE ELSE s.LOADINGTYPE END [FIN-DS Loading type],
	CONVERT(TEXT, k.STACKING) [REQUIREMENT Stacking],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.PARTNUMBER ELSE e.PARTNUMBER END [NSEDB PN],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.CMS ELSE e.CMS END [NSEDB CMS],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.DAL ELSE e.DAL END [NSEDB DAL],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.EQUIPMENTDESIGNATION ELSE e.EQUIPMENTDESIGNATION END [NSEDB Supplier Technological Designation],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.PTSREF ELSE e.PTSREF END [NSEDB PTS Document Reference],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.PTSISSUE ELSE e.PTSISSUE END [NSEDB PTS Reference Issue],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.DDPREF ELSE e.DDPREF END [NSEDB DDP Document Reference],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.DDPISSUE ELSE e.DDPISSUE END [NSEDB DDP Reference Issue],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.STATESTATE ELSE e.STATESTATE END [NSEDB State],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.CALCULATEDWEIGHT ELSE e.CALCULATEDWEIGHT END [NSEDB Calculated Weight Grammes],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.ESTIMATEDWEIGHTGRAMMES ELSE e.ESTIMATEDWEIGHTGRAMMES END [NSEDB Estimated Weight Grammes],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.GUARANTEEDWEIGHTGRAMMES ELSE e.GUARANTEEDWEIGHTGRAMMES END [NSEDB RFI RFP PTS Guaranteed Weigh Grammes],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.VALIDFORGROUNDTESTS ELSE e.VALIDFORGROUNDTESTS END [NSEDB For ground use only],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.SERIALISATION ELSE e.SERIALISATION END [NSEDB Serialisation],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.WEIGHTWEIGHTGRAMMES ELSE e.WEIGHTWEIGHTGRAMMES END [NSEDB Acceptance sheet weighed weight],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN ed.AC_ICDfolderVersion ELSE e.AC_ICDfolderVersion END [NSEDB AC/ICD Folder Version],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN pd.LOOKUPKEY ELSE p.LOOKUPKEY END [SUPPLIER FSCM],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN pd.DESCRIPTION_DOM ELSE p.DESCRIPTION_DOM END [SUPPLIER Name],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN qd.MODELREF ELSE q.MODELREF END [Model Reference],
	CASE WHEN sd.BWTPARTNUMBER IS NOT NULL THEN qd.MODELMATURITY ELSE q.MODELMATURITY END [Model Maturity],
	a.MPNUMBER [MP],
	a.MODNUMBER [MOD],
	i.BNAME + i.VERSIONIDA2VERSIONINFO [SI Reference],
	i.STATESTATE [SI State]
FROM
	tmp_MSNDefinition m
	JOIN tmpsv_FIN f ON f.BIDA2A2 = m.[FIN-CI BIDA2A2]
	LEFT JOIN tmpsv_DS s ON
		s.BIDA2A2 = m.[Serial FIN-DS BIDA2A2]
		AND s.STATESTATE <> ''''WIP''''
	LEFT JOIN tmpsv_PN e ON e.BIDA2A2 = s.IDPN
	LEFT JOIN tmpsv_SUPPLIER p ON p.LOOKUPKEY = e.FSCM
	LEFT JOIN tmpsv_EQUIPMENTMODEL q ON q.IDA2A2 = e.IDMODEL
	LEFT JOIN tmpsv_LOCATION n ON n.IDA2A2 = s.PANEL
	LEFT JOIN tmpsv_LOCATION z ON z.IDA2A2 = s.ZONE
	LEFT JOIN tmpsv_ANSICODE c ON c.IDA2A2 = s.ANSICODE
	LEFT JOIN tmpsv_DSMSNRANGE g ON g.BIDA2A2 = m.[Serial FIN-DS BIDA2A2]
	LEFT JOIN tmpsv_STACKCONC k ON k.IDA2A2 = m.[Serial DS REQUIREMENT IDA2A2]
	LEFT JOIN tmpsv_ACECIN a ON a.IDA2A2 = m.[CIN IDA2A2]
	LEFT JOIN tmpsv_DS sd ON sd.BIDA2A2 = m.[Development FIN-DS BIDA2A2]
	LEFT JOIN tmpsv_PN ed ON ed.BIDA2A2 = sd.IDPN
	LEFT JOIN tmpsv_SUPPLIER pd ON pd.LOOKUPKEY = ed.FSCM
	LEFT JOIN tmpsv_EQUIPMENTMODEL qd ON qd.IDA2A2 = ed.IDMODEL
	LEFT JOIN tmpsv_LOCATION nd ON nd.IDA2A2 = sd.PANEL
	LEFT JOIN tmpsv_LOCATION zd ON zd.IDA2A2 = sd.ZONE
	LEFT JOIN tmpsv_ANSICODE cd ON cd.IDA2A2 = sd.ANSICODE
	LEFT JOIN tmpsv_SI i ON i.BIDA2A2 = m.[SI BIDA2A2]
WHERE
	(
		s.BWTPARTNUMBER IS NOT NULL
		OR sd.BWTPARTNUMBER IS NOT NULL
	)
	AND (
		m.MSN = ''''#1#''''
		OR ''''#1#'''' = ''''''''
	)
	AND (
		m.ATA = ''''2325''''
		OR  m.ATA LIKE ''''45%''''
		OR  m.ATA LIKE ''''46%''''
		OR (f.FIN LIKE ''''%12XZ%'''' AND f.FIN LIKE ''''%SW%'''')
		OR (f.FIN LIKE ''''%46TH%'''' AND f.FIN LIKE ''''%SW%'''')
		OR (f.FIN LIKE ''''%7QM%'''' AND f.FIN LIKE ''''%SW%'''')
		OR (f.FIN LIKE ''''%TU%'''' AND f.FIN LIKE ''''%SW%'''')
		OR (f.FUNCTIONALDESIGNATION LIKE ''''%ACRIF%'''')
		OR (m.ATA LIKE ''''3813'''' AND f.FIN LIKE ''''%SW%'''')
	)
	AND f.Status <> ''''WIP''''
	AND f.FINCategory <> ''''SSPC''''
	AND f.FINCategory <> ''''LRI''''
	AND NOT f.FUNCTIONALDESIGNATION LIKE ''''%C/B%''''
	AND NOT f.FIN LIKE ''''%TX%''''
	AND NOT f.FIN LIKE ''''%RF%''''
	AND NOT f.FIN LIKE ''''%TJ%'''''')',
	'- CSV format',
	'export_csv.php',
	'MSN :#1#',
	'Only FIN having 1 FIN-DS effective (Serial or Dev), Only 1 DS FIN-DS (Dev else Serial), including Filters for MIS',
	NULL,
	@AttGroup
)
