DECLARE @id_ds AS INT, 
	@idr_ata AS INT, 
	@ata AS VARCHAR(8000),
	@idr_fin AS INT, 
	@fin AS VARCHAR(8000), 
	@mp AS VARCHAR(8000), 
	@idr_mp AS INT, 
	@EDDReference AS VARCHAR(8000),
	@DSRefRecup AS VARCHAR (8000),
	@DSRef AS VARCHAR (8000)

DECLARE 	
	@RefDS AS VARCHAR (8000),
	@EDDComment AS VARCHAR (8000),
	@DeviceType AS VARCHAR (8000),
	@Rating AS VARCHAR (8000),
	@PowerCenter AS VARCHAR (8000),
	@PowerCenterType AS VARCHAR (8000),
	@GroundServiceSupply AS VARCHAR (8000), 
	@Busbar AS VARCHAR (8000),
	@SubBusBar AS VARCHAR (8000),                
	@Allocated AS VARCHAR (8000),
	@PhaseType AS VARCHAR (8000),
	@NominalPower AS VARCHAR (8000),
	@NPP1 AS VARCHAR (8000),
	@NPP2 AS VARCHAR (8000),
	@NPP3 AS VARCHAR (8000),
	@powerfactor AS VARCHAR (8000),
	@InrushCur AS VARCHAR (8000),
	@InrushDur AS VARCHAR (8000),
	@Classification AS VARCHAR (8000),
	@Family AS VARCHAR (8000),
	@MaxMode AS VARCHAR (8000),
	@Sheddable AS VARCHAR (8000),
	@TypeACDC AS VARCHAR (8000),
	@Monitored AS VARCHAR (8000),
	@SecuredMaxen AS VARCHAR (8000),
	@FullPrevision AS VARCHAR (8000),
	@EDDMix AS VARCHAR (8000),
	@Group_ AS VARCHAR (8000),        
	@Priority AS VARCHAR (8000),
	@FlightPriority AS VARCHAR (8000),
	@SysGPriority AS VARCHAR (8000),
	@SysFPriority AS VARCHAR (8000),
	@Location AS VARCHAR (8000),
	@Poc AS VARCHAR (8000),
	@PinAllocation AS VARCHAR (8000),
	@Designation AS VARCHAR (8000),
	@GroundServOp AS VARCHAR (8000), 
	@TurnAround0015Op AS VARCHAR (8000),
	@TurnAround1530Op AS VARCHAR (8000),
	@TurnAround3045Op AS VARCHAR (8000),
	@TurnAround4560Op AS VARCHAR (8000),
	@TurnAround6075Op AS VARCHAR (8000),
	@TurnAround7590Op AS VARCHAR (8000),
	@TurnAround90105Op AS VARCHAR (8000),
	@TurnAround105120Op AS VARCHAR (8000),
	@TurnAround120135Op AS VARCHAR (8000),
	@TurnAround135150Op AS VARCHAR (8000),
	@PushBackOp AS VARCHAR (8000),
	@StartOp AS VARCHAR (8000),
	@RollOp AS VARCHAR (8000),
	@TakeOffOp AS VARCHAR (8000),
	@ClimbOp AS VARCHAR (8000),
	@CruiseOp AS VARCHAR (8000),
	@DescentOp AS VARCHAR (8000),
	@LandingOp AS VARCHAR (8000),
	@TaxiOp AS VARCHAR (8000),
	@SpareOp AS VARCHAR (8000),
	@EmerConfOp AS VARCHAR (8000),
	@EmerConfOutOp AS VARCHAR (8000),
	@BatConfOp AS VARCHAR (8000),
	@GroundServMax AS VARCHAR (8000),  
	@TurnAround0015Max AS VARCHAR (8000),
	@TurnAround1530Max AS VARCHAR (8000),
	@TurnAround3045Max AS VARCHAR (8000),
	@TurnAround4560Max AS VARCHAR (8000),
	@TurnAround6075Max AS VARCHAR (8000),
	@TurnAround7590Max AS VARCHAR (8000),
	@TurnAround90105Max AS VARCHAR (8000),
	@TurnAround105120Max AS VARCHAR (8000),
	@TurnAround120135Max AS VARCHAR (8000),
	@TurnAround135150Max AS VARCHAR (8000),
	@PushBackMax AS VARCHAR (8000),
	@StartMax AS VARCHAR (8000),
	@RollMax AS VARCHAR (8000),
	@TakeOffMax AS VARCHAR (8000),
	@ClimbMax AS VARCHAR (8000),
	@CruiseMax AS VARCHAR (8000),
	@DescentMax AS VARCHAR (8000),
	@LandingMax AS VARCHAR (8000),
	@TaxiMax AS VARCHAR (8000),
	@SpareMax AS VARCHAR (8000),
	@EmerConfMax AS VARCHAR (8000),
	@EmerConfOutMax AS VARCHAR (8000),
	@BatConfMax AS VARCHAR (8000)


DECLARE CURSOR_idr_EEPDC CURSOR FOR
SELECT 
	EEPDC.[FIN],
	EEPDC.[MP],	
	EEPDC.[Reference DS/SI],
	EEPDC.[EDD Comment],
	EEPDC.[Device Type],
	EEPDC.[Rating (A) CIRCE],
	EEPDC.[Power Center],
	EEPDC.[Power Center Type],
	EEPDC.[Ground Service Supply],
	EEPDC.[Busbar],
	EEPDC.[Sub Busbar],
	EEPDC.[Allocated Phase],
	EEPDC.[Phase Type],
	EEPDC.[Nominal Power (W or V#A)],
	EEPDC.[Nominal Power PhA (V#A)],
	EEPDC.[Nominal Power PhB (V#A)],
	EEPDC.[Nominal Power PhC (V#A)],
	EEPDC.[Power Factor],
	EEPDC.[Inrush Current (A)],
	EEPDC.[Inrush Duration (ms)],
	EEPDC.[Classification],
	EEPDC.[Family],
	EEPDC.[Operating Mode],
	EEPDC.[Sheddable],
	EEPDC.[AC/DC Type],
	EEPDC.[Monitored by CBMF],
	EEPDC.[Secured Open],
	EEPDC.[Full Provision Status],
	EEPDC.[EDD Option],
	EEPDC.[Group],
	EEPDC.[Airline Ground Priority],
	EEPDC.[Airline Flight Priority],
	EEPDC.[System Ground Priority],
	EEPDC.[System Flight Priority],
	EEPDC.[Location],
	EEPDC.[Power Output Connector],
	EEPDC.[Power Output Pin Allocation],
	EEPDC.[Designation],
	EEPDC.[GND SERV#Op],
	EEPDC.[0 to 15Op],
	EEPDC.[15 to 30Op],
	EEPDC.[30 to 45Op],
	EEPDC.[45 to 60Op],
	EEPDC.[60 to 75Op],
	EEPDC.[75 to 90Op],
	EEPDC.[90 to 105Op],
	EEPDC.[105 to 120Op],
	EEPDC.[120 to 135Op],
	EEPDC.[135 to 150Op],
	EEPDC.[PUSHBACKOp],
	EEPDC.[STARTOp],
	EEPDC.[ROLLOp],
	EEPDC.[TAKE OFFOp],
	EEPDC.[CLIMBOp],
	EEPDC.[CRUISEOp],
	EEPDC.[DESCENTOp],
	EEPDC.[LANDINGOp],
	EEPDC.[TAXIOp],
	EEPDC.[SPAREOp],
	EEPDC.[GEN# INOPERATIVEOp],
	EEPDC.[FLAME OUTOp],
	EEPDC.[BATT# ONLYOp],
	EEPDC.[GND SERV#MAX],
	EEPDC.[0 to 15MAX],
	EEPDC.[15 to 30MAX],
	EEPDC.[30 to 45MAX],
	EEPDC.[45 to 60MAX],
	EEPDC.[60 to 75MAX],
	EEPDC.[75 to 90MAX],
	EEPDC.[90 to 105MAX],
	EEPDC.[105 to 120MAX],
	EEPDC.[120 to 135MAX],
	EEPDC.[135 to 150MAX],
	EEPDC.[PUSHBACKMAX],
	EEPDC.[STARTMAX],
	EEPDC.[ROLLMAX],
	EEPDC.[TAKE OFFMAX],
	EEPDC.[CLIMBMAX],
	EEPDC.[CRUISEMAX],
	EEPDC.[DESCENTMAX],
	EEPDC.[LANDINGMAX],
	EEPDC.[TAXIMAX],
	EEPDC.[SPAREMAX],
	EEPDC.[GEN# INOPERATIVEMAX],
	EEPDC.[FLAME OUTMAX],
	EEPDC.[BATT# ONLYMAX] 
FROM EEPDC

OPEN CURSOR_idr_EEPDC
-- Perform the first fetch.
FETCH NEXT FROM CURSOR_idr_EEPDC INTO

	@FIN,
	@mp,
	@RefDS,
	@EDDComment,
	@DeviceType,
	@Rating ,
	@PowerCenter ,
	@PowerCenterType ,
	@GroundServiceSupply , 
	@Busbar ,
	@SubBusBar ,                
	@Allocated,
	@PhaseType,
	@NominalPower ,
	@NPP1 ,
	@NPP2 ,
	@NPP3 ,
	@powerfactor ,
	@InrushCur ,
	@InrushDur,
	@Classification ,
	@Family ,
	@MaxMode ,
	@Sheddable ,
	@TypeACDC ,
	@Monitored ,
	@SecuredMaxen ,
	@FullPrevision ,
	@EDDMix,
	@Group_ ,        
	@Priority ,
	@FlightPriority ,
	@SysGPriority ,
	@SysFPriority ,
	@Location,
	@Poc,
	@PinAllocation ,
	@Designation,
	@GroundServOp , 
	@TurnAround0015Op ,
	@TurnAround1530Op ,
	@TurnAround3045Op ,
	@TurnAround4560Op ,
	@TurnAround6075Op ,
	@TurnAround7590Op ,
	@TurnAround90105Op ,
	@TurnAround105120Op ,
	@TurnAround120135Op ,
	@TurnAround135150Op ,
	@PushBackOp ,
	@StartOp ,
	@RollOp ,
	@TakeOffOp ,
	@ClimbOp ,
	@CruiseOp ,
	@DescentOp ,
	@LandingOp ,
	@TaxiOp ,
	@SpareOp ,
	@EmerConfOp ,
	@EmerConfOutOp ,
	@BatConfOp,
	@GroundServMax ,  
	@TurnAround0015Max ,
	@TurnAround1530Max ,
	@TurnAround3045Max ,
	@TurnAround4560Max ,
	@TurnAround6075Max ,
	@TurnAround7590Max ,
	@TurnAround90105Max ,
	@TurnAround105120Max ,
	@TurnAround120135Max ,
	@TurnAround135150Max ,
	@PushBackMax ,
	@StartMax ,
	@RollMax ,
	@TakeOffMax ,
	@ClimbMax ,
	@CruiseMax ,
	@DescentMax ,
	@LandingMax ,
	@TaxiMax ,
	@SpareMax ,
	@EmerConfMax ,
	@EmerConfOutMax ,
	@BatConfMax 


WHILE @@FETCH_STATUS = 0
BEGIN  

	SET @idr_fin = ''
	SET @idr_mp = ''
	
	-- GET ata
	SELECT @ATA = ATA 
	FROM EEPDC_FIN_ATA
	WHERE EEPDC_FIN_ATA.FIN = @FIN

	SELECT @idr_ata = id_ata 
	FROM R_ATA
	WHERE R_ATA.ATACode = @ATA
	
	-- GET FIN id
	SELECT @idr_fin = id_fin 
	FROM R_FIN_CI
	WHERE R_FIN_CI.FIN = @FIN
	
	UPDATE R_FIN_CI set FunctionnalDesignation = @DeviceType + ' ' +@Designation, idr_ata = @idr_ata where id_fin = @idr_fin
	
	-- Get MP id
	SELECT @idr_mp = id_MP 
	FROM T_MP
	WHERE T_MP.MPReference = @mp
	
	SET @id_ds = ''
	
	-- Test si l'EDD est d‰j€ pr‰sent
	SELECT @id_ds = id_ds FROM R_FIN_DS
	WHERE idr_fin = @idr_fin
	AND idr_mp = @idr_mp
	AND DS_SI_Reference = @RefDS

	SET @DSRefRecup = ''
	select @DSRefRecup = max(DS_SI_Reference) + 1 from R_FIN_DS where idr_fin = @idr_fin and idr_mp = @idr_mp
	IF @DSRefRecup ='' or @DSRefRecup is null
	BEGIN
		SET @DSRef = '0001'
	END 
	ELSE
	BEGIN
		Set @DSRef = '000' + @DSRefRecup
	END
	
	SELECT
		@EDDReference = ATACode + Circuit_Letter + EEPDC.[AC/DC Type] +
		REPLICATE('0', 6 - LEN(CONVERT(VARCHAR(8000), ISNULL((SELECT MAX(CONVERT(INTEGER, SUBSTRING(EDDReference, 9, 6)) + 1) FROM R_FIN_DS WHERE LEFT(EDDReference, 4) = ATACode), 0)))) + CONVERT(VARCHAR(8000),ISNULL((SELECT MAX(CONVERT(INTEGER, SUBSTRING(EDDReference, 9, 6)) + 1) FROM R_FIN_DS WHERE LEFT(EDDReference, 4) = ATACode), 0))
		+ 'V000'
	FROM
		EEPDC
	        JOIN R_FIN_CI ON R_FIN_CI.FIN = EEPDC.[FIN]
	        JOIN R_ATA ON R_ATA.id_ata = R_FIN_CI.idr_ata
	WHERE R_FIN_CI.FIN = @FIN

IF @id_ds <> '' 
BEGIN
	UPDATE R_FIN_DS SET
	
		R_FIN_DS.EDDReference = @EDDReference,  
		R_FIN_DS.DS_SI_Reference = @RefDS,
		R_FIN_DS.EDDComment = @EDDComment,
		R_FIN_DS.TypeOfProtection = @DeviceType,
		R_FIN_DS.Rating = REPLACE(@Rating,',','.'),
		R_FIN_DS.Panel = @PowerCenter ,
		R_FIN_DS.PowerCenterType = @PowerCenterType ,
		R_FIN_DS.GroundServiceSupply = @GroundServiceSupply , 
		R_FIN_DS.Busbar = @Busbar ,
		R_FIN_DS.SubBusBar = @SubBusBar ,                
		R_FIN_DS.AllocatedPhase = @Allocated,
		R_FIN_DS.TypePhase = @PhaseType,
		R_FIN_DS.NominalPower = REPLACE(@NominalPower,',','.'),
		R_FIN_DS.NPP1 = 
		CASE
			WHEN @NPP1 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP1,',','.'))
			ELSE NULL
		END,
		R_FIN_DS.NPP2 = 	
		CASE
			WHEN @NPP2 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP2,',','.'))
			ELSE NULL
		END,
		R_FIN_DS.NPP3 = 
		CASE
			WHEN @NPP3 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP3,',','.'))
			ELSE NULL
		END,
		R_FIN_DS.PowerFactor = REPLACE(@powerfactor,',','.'),
		R_FIN_DS.InrushCurrent = @InrushCur,
		R_FIN_DS.Duration = @InrushDur,
		R_FIN_DS.Classification = @Classification ,
		R_FIN_DS.FamilyLoad = @Family,
		R_FIN_DS.OperationalBehaviour = @MaxMode,
		R_FIN_DS.Sheddable = @Sheddable ,
		R_FIN_DS.Side = 1,
		R_FIN_DS.TypeACDC = @TypeACDC ,
		R_FIN_DS.Monitored = @Monitored,
		R_FIN_DS.SecuredOpen = @SecuredMaxen,
		R_FIN_DS.FullProvisionStatus = @FullPrevision,
		R_FIN_DS.EDDOption = @EDDMix,
		R_FIN_DS.Group_ = @Group_ ,        
		R_FIN_DS.Priority = @Priority ,
		R_FIN_DS.FlightPriority = @FlightPriority ,
		R_FIN_DS.SysGPriority = @SysGPriority ,
		R_FIN_DS.SysFPriority = @SysFPriority ,
		R_FIN_DS.Location = @Location,
		R_FIN_DS.ReferenceConnector = @Poc,
		R_FIN_DS.PINAllocation = @PinAllocation ,
		R_FIN_DS.EDDFuncDesignation = @Designation,
		R_FIN_DS.GroundServOp = CONVERT(NUMERIC,CONVERT(FLOAT,@GroundServOp)),
		R_FIN_DS.TurnAround0015Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround0015Op)),
		R_FIN_DS.TurnAround1530Op =CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround1530Op)),
		R_FIN_DS.TurnAround3045Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround3045Op)),
		R_FIN_DS.TurnAround4560Op =CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround4560Op)),
		R_FIN_DS.TurnAround6075Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround6075Op)),
		R_FIN_DS.TurnAround7590Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround7590Op)),
		R_FIN_DS.TurnAround90105Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround90105Op)),
		R_FIN_DS.TurnAround105120Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround105120Op)),
		R_FIN_DS.TurnAround120135Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround120135Op)),
		R_FIN_DS.TurnAround135150Op = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround135150Op)),
		R_FIN_DS.PushBackOp = CONVERT(NUMERIC,CONVERT(FLOAT,@PushBackOp)),
		R_FIN_DS.StartOp = CONVERT(NUMERIC,CONVERT(FLOAT,@StartOp)),
		R_FIN_DS.RollOp = CONVERT(NUMERIC,CONVERT(FLOAT,@RollOp)),
		R_FIN_DS.TakeOffOp = CONVERT(NUMERIC,CONVERT(FLOAT,@TakeOffOp)),
		R_FIN_DS.ClimbOp = CONVERT(NUMERIC,CONVERT(FLOAT,@ClimbOp)),
		R_FIN_DS.CruiseOp = CONVERT(NUMERIC,CONVERT(FLOAT,@CruiseOp)),
		R_FIN_DS.DescentOp = CONVERT(NUMERIC,CONVERT(FLOAT,@DescentOp)),
		R_FIN_DS.LandingOp = CONVERT(NUMERIC,CONVERT(FLOAT,@LandingOp)),
		R_FIN_DS.TaxiOp = CONVERT(NUMERIC,CONVERT(FLOAT,@TaxiOp)),
		R_FIN_DS.SpareOp = CONVERT(NUMERIC,CONVERT(FLOAT,@SpareOp)),
		R_FIN_DS.EmerConfOp = CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOp)),
		R_FIN_DS.EmerConfOutOp = CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOutOp)),
		R_FIN_DS.BatConfOp = CONVERT(NUMERIC,CONVERT(FLOAT,@BatConfOp)),
		R_FIN_DS.GroundServMax = CONVERT(NUMERIC,CONVERT(FLOAT,@GroundServMax)),
		R_FIN_DS.TurnAround0015Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround0015Max)),
		R_FIN_DS.TurnAround1530Max =CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround1530Max)),
		R_FIN_DS.TurnAround3045Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround3045Max)),
		R_FIN_DS.TurnAround4560Max =CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround4560Max)),
		R_FIN_DS.TurnAround6075Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround6075Max)),
		R_FIN_DS.TurnAround7590Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround7590Max)),
		R_FIN_DS.TurnAround90105Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround90105Max)),
		R_FIN_DS.TurnAround105120Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround105120Max)),
		R_FIN_DS.TurnAround120135Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround120135Max)),
		R_FIN_DS.TurnAround135150Max = CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround135150Max)),
		R_FIN_DS.PushBackMax = CONVERT(NUMERIC,CONVERT(FLOAT,@PushBackMax)),
		R_FIN_DS.StartMax = CONVERT(NUMERIC,CONVERT(FLOAT,@StartMax)),
		R_FIN_DS.RollMax = CONVERT(NUMERIC,CONVERT(FLOAT,@RollMax)),
		R_FIN_DS.TakeOffMax = CONVERT(NUMERIC,CONVERT(FLOAT,@TakeOffMax)),
		R_FIN_DS.ClimbMax = CONVERT(NUMERIC,CONVERT(FLOAT,@ClimbMax)),
		R_FIN_DS.CruiseMax = CONVERT(NUMERIC,CONVERT(FLOAT,@CruiseMax)),
		R_FIN_DS.DescentMax = CONVERT(NUMERIC,CONVERT(FLOAT,@DescentMax)),
		R_FIN_DS.LandingMax = CONVERT(NUMERIC,CONVERT(FLOAT,@LandingMax)),
		R_FIN_DS.TaxiMax = CONVERT(NUMERIC,CONVERT(FLOAT,@TaxiMax)),
		R_FIN_DS.SpareMax = CONVERT(NUMERIC,CONVERT(FLOAT,@SpareMax)),
		R_FIN_DS.EmerConfMax = CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfMax)),
		R_FIN_DS.EmerConfOutMax = CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOutMax)),
		R_FIN_DS.BatConfMax = CONVERT(NUMERIC,CONVERT(FLOAT,@BatConfMax)),
		R_FIN_DS.ds_type = 4,
	        R_FIN_DS.MG = 0,
		R_FIN_DS.VALM0 = 'Not Validated',
		R_FIN_DS.VALM1 = 'Not Validated',
		R_FIN_DS.VALM2 = 'Not Validated'
		
	Where id_ds = @id_ds
END
ELSE
BEGIN
	INSERT INTO R_FIN_DS
	(
		DS_SI_Reference,
		idr_fin, 
		idr_mp,
		EDDReference,  
		
		EDDComment  ,
		TypeOfProtection  ,
		Rating ,
		Panel   ,
		Side,
		PowerCenterType   ,
		GroundServiceSupply   , 
		Busbar   ,
		SubBusBar   ,                
		AllocatedPhase  ,
		TypePhase  ,
		NominalPower ,
		NPP1   ,
		NPP2   ,
		NPP3   ,
		PowerFactor  ,
		InrushCurrent  ,
		Duration  ,
		Classification   ,
		FamilyLoad  ,
		OperationalBehaviour  ,
		Sheddable   ,
		TypeACDC   ,
		Monitored  ,
		SecuredOpen  ,
		FullProvisionStatus  ,
		EDDOption  ,
		Group_   ,        
		Priority   ,
		FlightPriority   ,
		SysGPriority   ,
		SysFPriority   ,
		Location  ,
		ReferenceConnector  ,
		PINAllocation   ,
		EDDFuncDesignation  ,
		GroundServOp   , 
		TurnAround0015Op   ,
		TurnAround1530Op   ,
		TurnAround3045Op   ,
		TurnAround4560Op   ,
		TurnAround6075Op   ,
		TurnAround7590Op   ,
		TurnAround90105Op   ,
		TurnAround105120Op   ,
		TurnAround120135Op   ,
		TurnAround135150Op   ,
		PushBackOp   ,
		StartOp   ,
		RollOp   ,
		TakeOffOp   ,
		ClimbOp   ,
		CruiseOp   ,
		DescentOp   ,
		LandingOp   ,
		TaxiOp   ,
		SpareOp   ,
		EmerConfOp   ,
		EmerConfOutOp   ,
		BatConfOp  ,
		GroundServMax   ,  
		TurnAround0015Max   ,
		TurnAround1530Max   ,
		TurnAround3045Max   ,
		TurnAround4560Max   ,
		TurnAround6075Max   ,
		TurnAround7590Max   ,
		TurnAround90105Max   ,
		TurnAround105120Max   ,
		TurnAround120135Max  ,
		TurnAround135150Max   ,
		PushBackMax   ,
		StartMax   ,
		RollMax   ,
		TakeOffMax   ,
		ClimbMax   ,
		CruiseMax   ,
		DescentMax   ,
		LandingMax   ,
		TaxiMax   ,
		SpareMax   ,
		EmerConfMax   ,
		EmerConfOutMax   ,
		BatConfMax  ,
		ds_type ,
        MG  ,
        VALM0 ,
        VALM1 ,
        VALM2 
    )
    VALUES
    (
    @DSRef,
    @idr_fin,
    @idr_mp,
    @EDDReference,  
	
	  @EDDComment,
	  @DeviceType,
	  CONVERT(FLOAT,REPLACE(@Rating,',','.')),
	  @PowerCenter ,
	  1,
	  @PowerCenterType ,
	  @GroundServiceSupply , 
	  @Busbar ,
	  @SubBusBar ,                
	  @Allocated,
	  @PhaseType,
	  CONVERT(FLOAT,REPLACE(@NominalPower,',','.')),
	  	
	CASE
		WHEN @NPP1 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP1,',','.'))
		ELSE NULL
	END,
	  
	CASE
		WHEN @NPP2 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP2,',','.'))
		ELSE NULL
	END,
	  
	CASE
		WHEN @NPP3 <> 'N/A' THEN CONVERT(FLOAT,REPLACE(@NPP3,',','.'))
		ELSE NULL
	END,
	  CONVERT(FLOAT,REPLACE(@powerfactor,',','.')),
	  CONVERT(FLOAT,REPLACE(@InrushCur,',','.')),
	  CONVERT(FLOAT,REPLACE(@InrushDur,',','.')),
	  @Classification ,
	  @Family,
	  @MaxMode,
	  @Sheddable ,
	  @TypeACDC ,
	  @Monitored,
	  @SecuredMaxen,
	  @FullPrevision,
	  @EDDMix,
	  @Group_ ,        
	  @Priority ,
	  @FlightPriority ,
	  @SysGPriority ,
	  @SysFPriority ,
	  @Location,
	  @Poc,
	  @PinAllocation ,
	  @Designation,
	  CONVERT(NUMERIC,CONVERT(FLOAT,@GroundServOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround0015Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround1530Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround3045Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround4560Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround6075Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround7590Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround90105Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround105120Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround120135Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround135150Op)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@PushBackOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@StartOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@RollOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TakeOffOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@ClimbOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@CruiseOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@DescentOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@LandingOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TaxiOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@SpareOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOutOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@BatConfOp)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@GroundServMax)),  
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround0015Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround1530Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround3045Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround4560Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround6075Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround7590Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround90105Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround105120Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround120135Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TurnAround135150Max)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@PushBackMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@StartMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@RollMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TakeOffMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@ClimbMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@CruiseMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@DescentMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@LandingMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@TaxiMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@SpareMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@EmerConfOutMax)),
	  CONVERT(NUMERIC,CONVERT(FLOAT,@BatConfMax)),
	  4,
          0,
          'Not Validated',
          'Not Validated',
          'Not Validated'
    )
END



FETCH NEXT FROM CURSOR_idr_EEPDC INTO
	@FIN,
	@mp,
	@RefDS,
	@EDDComment,
	@DeviceType,
	@Rating ,
	@PowerCenter ,
	@PowerCenterType ,
	@GroundServiceSupply , 
	@Busbar ,
	@SubBusBar ,                
	@Allocated,
	@PhaseType,
	@NominalPower ,
	@NPP1 ,
	@NPP2 ,
	@NPP3 ,
	@powerfactor ,
	@InrushCur,
	@InrushDur,
	@Classification ,
	@Family,
	@MaxMode,
	@Sheddable ,
	@TypeACDC ,
	@Monitored,
	@SecuredMaxen,
	@FullPrevision,
	@EDDMix,
	@Group_ ,        
	@Priority ,
	@FlightPriority ,
	@SysGPriority ,
	@SysFPriority ,
	@Location,
	@Poc,
	@PinAllocation ,
	@Designation,
	@GroundServOp , 
	@TurnAround0015Op ,
	@TurnAround1530Op ,
	@TurnAround3045Op ,
	@TurnAround4560Op ,
	@TurnAround6075Op ,
	@TurnAround7590Op ,
	@TurnAround90105Op ,
	@TurnAround105120Op ,
	@TurnAround120135Op ,
	@TurnAround135150Op ,
	@PushBackOp ,
	@StartOp ,
	@RollOp ,
	@TakeOffOp ,
	@ClimbOp ,
	@CruiseOp ,
	@DescentOp ,
	@LandingOp ,
	@TaxiOp ,
	@SpareOp ,
	@EmerConfOp ,
	@EmerConfOutOp ,
	@BatConfOp,
	@GroundServMax ,  
	@TurnAround0015Max ,
	@TurnAround1530Max ,
	@TurnAround3045Max ,
	@TurnAround4560Max ,
	@TurnAround6075Max ,
	@TurnAround7590Max ,
	@TurnAround90105Max ,
	@TurnAround105120Max ,
	@TurnAround120135Max ,
	@TurnAround135150Max ,
	@PushBackMax ,
	@StartMax ,
	@RollMax ,
	@TakeOffMax ,
	@ClimbMax ,
	@CruiseMax ,
	@DescentMax ,
	@LandingMax ,
	@TaxiMax ,
	@SpareMax ,
	@EmerConfMax ,
	@EmerConfOutMax ,
	@BatConfMax 


END
CLOSE CURSOR_idr_EEPDC
DEALLOCATE CURSOR_idr_EEPDC
        
        
        
        
